/*
* Copyright (c) 2020-present SMC Treviso s.r.l. All rights reserved.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { OpenApiRestClient } from './OpenApiRestClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AutoGenerateDocTypesRequest } from './models/AutoGenerateDocTypesRequest';
export { BehaviorMergeType } from './models/BehaviorMergeType';
export { BehaviorOnError } from './models/BehaviorOnError';
export type { Bucket } from './models/Bucket';
export type { BucketDTO } from './models/BucketDTO';
export { ChunkType } from './models/ChunkType';
export { CombinationTechnique } from './models/CombinationTechnique';
export type { CurrentBucket } from './models/CurrentBucket';
export type { DataIndex } from './models/DataIndex';
export type { DataIndexByDocTypes } from './models/DataIndexByDocTypes';
export type { DataIndexDTO } from './models/DataIndexDTO';
export type { Datasource } from './models/Datasource';
export type { DatasourceDTO } from './models/DatasourceDTO';
export type { DatasourceHealthStatus } from './models/DatasourceHealthStatus';
export type { DatasourceJobStatus } from './models/DatasourceJobStatus';
export type { DatasourceMessage } from './models/DatasourceMessage';
export type { DocType } from './models/DocType';
export type { DocTypeDTO } from './models/DocTypeDTO';
export type { DocTypeField } from './models/DocTypeField';
export type { DocTypeFieldDTO } from './models/DocTypeFieldDTO';
export type { DocTypeFieldResponseDTO } from './models/DocTypeFieldResponseDTO';
export type { DocTypeTemplate } from './models/DocTypeTemplate';
export type { DocTypeTemplateDTO } from './models/DocTypeTemplateDTO';
export type { EnrichItem } from './models/EnrichItem';
export type { EnrichItemDTO } from './models/EnrichItemDTO';
export { EnrichItemType } from './models/EnrichItemType';
export type { EnrichPipeline } from './models/EnrichPipeline';
export type { EnrichPipelineDTO } from './models/EnrichPipelineDTO';
export { EventType } from './models/EventType';
export { FieldType } from './models/FieldType';
export type { FieldValue } from './models/FieldValue';
export type { FormField } from './models/FormField';
export { FormFieldType } from './models/FormFieldType';
export type { FormFieldValidator } from './models/FormFieldValidator';
export type { FormTemplate } from './models/FormTemplate';
export type { GetMappingsOrSettingsFromDocTypesRequest } from './models/GetMappingsOrSettingsFromDocTypesRequest';
export { HealthStatus } from './models/HealthStatus';
export type { HybridSearchPipelineDTO } from './models/HybridSearchPipelineDTO';
export { JobStatus } from './models/JobStatus';
export type { JsonObject } from './models/JsonObject';
export { K9Column } from './models/K9Column';
export type { K9EntityEventBucket } from './models/K9EntityEventBucket';
export type { K9EntityEventDataIndex } from './models/K9EntityEventDataIndex';
export type { K9EntityEventDatasource } from './models/K9EntityEventDatasource';
export type { K9EntityEventDocType } from './models/K9EntityEventDocType';
export type { K9EntityEventDocTypeTemplate } from './models/K9EntityEventDocTypeTemplate';
export type { K9EntityEventEnrichItem } from './models/K9EntityEventEnrichItem';
export type { K9EntityEventEnrichPipeline } from './models/K9EntityEventEnrichPipeline';
export type { K9EntityEventPluginDriver } from './models/K9EntityEventPluginDriver';
export type { K9EntityEventSuggestionCategory } from './models/K9EntityEventSuggestionCategory';
export type { KeycloakSettings } from './models/KeycloakSettings';
export type { Language } from './models/Language';
export { NormalizationTechnique } from './models/NormalizationTechnique';
export type { OffsetDateTime } from './models/OffsetDateTime';
export type { PageBucket } from './models/PageBucket';
export type { PageDataIndex } from './models/PageDataIndex';
export type { PageDatasource } from './models/PageDatasource';
export type { PageDocType } from './models/PageDocType';
export type { PageDocTypeField } from './models/PageDocTypeField';
export type { PageDocTypeTemplate } from './models/PageDocTypeTemplate';
export type { PageEnrichItem } from './models/PageEnrichItem';
export type { PageEnrichPipeline } from './models/PageEnrichPipeline';
export type { PagePluginDriver } from './models/PagePluginDriver';
export type { PageSuggestionCategory } from './models/PageSuggestionCategory';
export type { PluginDriver } from './models/PluginDriver';
export type { PluginDriverDocType } from './models/PluginDriverDocType';
export type { PluginDriverDocTypesDTO } from './models/PluginDriverDocTypesDTO';
export type { PluginDriverDTO } from './models/PluginDriverDTO';
export type { PluginDriverHealthDTO } from './models/PluginDriverHealthDTO';
export { PluginDriverType } from './models/PluginDriverType';
export { Provisioning } from './models/Provisioning';
export type { QueryAnalysis } from './models/QueryAnalysis';
export { RetrieveType } from './models/RetrieveType';
export type { SearchConfig } from './models/SearchConfig';
export type { SearchPipelineResponseDTO } from './models/SearchPipelineResponseDTO';
export type { SortingResponseDTO } from './models/SortingResponseDTO';
export { Status } from './models/Status';
export type { StatusResponse } from './models/StatusResponse';
export type { SuggestionCategory } from './models/SuggestionCategory';
export type { SuggestionCategoryDTO } from './models/SuggestionCategoryDTO';
export type { TabResponseDTO } from './models/TabResponseDTO';
export type { TemplateResponseDTO } from './models/TemplateResponseDTO';
export { TemplateType } from './models/TemplateType';
export type { TokenTabResponseDTO } from './models/TokenTabResponseDTO';
export type { TriggerResourceDTO } from './models/TriggerResourceDTO';
export type { TriggerV2ResourceDTO } from './models/TriggerV2ResourceDTO';
export type { Tuple2BucketDatasource } from './models/Tuple2BucketDatasource';
export type { Tuple2BucketSuggestionCategory } from './models/Tuple2BucketSuggestionCategory';
export type { Tuple2DataIndexDocType } from './models/Tuple2DataIndexDocType';
export type { Tuple2DatasourceDataIndex } from './models/Tuple2DatasourceDataIndex';
export type { Tuple2DatasourceEnrichPipeline } from './models/Tuple2DatasourceEnrichPipeline';
export type { Tuple2DatasourcePluginDriver } from './models/Tuple2DatasourcePluginDriver';
export type { Tuple2DocTypeDocTypeField } from './models/Tuple2DocTypeDocTypeField';
export type { Tuple2DocTypeLong } from './models/Tuple2DocTypeLong';
export type { Tuple2EnrichPipelineEnrichItem } from './models/Tuple2EnrichPipelineEnrichItem';
export type { Tuple2SuggestionCategoryDocTypeField } from './models/Tuple2SuggestionCategoryDocTypeField';

export { BucketResourceService } from './services/BucketResourceService';
export { DataIndexResourceService } from './services/DataIndexResourceService';
export { DatasourceEventResourceService } from './services/DatasourceEventResourceService';
export { DatasourceResourceService } from './services/DatasourceResourceService';
export { DateFilterResourceService } from './services/DateFilterResourceService';
export { DocTypeResourceService } from './services/DocTypeResourceService';
export { EnrichItemResourceService } from './services/EnrichItemResourceService';
export { EnrichPipelineResourceService } from './services/EnrichPipelineResourceService';
export { KeycloakSettingsResourceService } from './services/KeycloakSettingsResourceService';
export { PipelineResourceService } from './services/PipelineResourceService';
export { PluginDriverFieldResourceService } from './services/PluginDriverFieldResourceService';
export { PluginDriverResourceService } from './services/PluginDriverResourceService';
export { ReindexResourceService } from './services/ReindexResourceService';
export { SchedulerResourceService } from './services/SchedulerResourceService';
export { SearchConfigResourceService } from './services/SearchConfigResourceService';
export { SuggestionCategoryResourceService } from './services/SuggestionCategoryResourceService';
export { TemplateResourceService } from './services/TemplateResourceService';
export { TriggerResourceService } from './services/TriggerResourceService';
export { TriggerWithDateResourceService } from './services/TriggerWithDateResourceService';

