/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum ChunkType {
    CHUNK_TYPE_DEFAULT = 'CHUNK_TYPE_DEFAULT',
    CHUNK_TYPE_TEXT_SPLITTER = 'CHUNK_TYPE_TEXT_SPLITTER',
    CHUNK_TYPE_TOKEN_TEXT_SPLITTER = 'CHUNK_TYPE_TOKEN_TEXT_SPLITTER',
    CHUNK_TYPE_CHARACTER_TEXT_SPLITTER = 'CHUNK_TYPE_CHARACTER_TEXT_SPLITTER',
    CHUNK_TYPE_SEMANTIC_SPLITTER = 'CHUNK_TYPE_SEMANTIC_SPLITTER',
    UNRECOGNIZED = 'UNRECOGNIZED',
}
