include:
  - path:
      - compose.yaml
services:
  rag-module:
    image: smclab/openk9-rag-module:${IMAGE_TAG:-2026.1.0-SNAPSHOT}
    container_name: openk9-rag-module
    hostname: openk9-rag-module
    environment:
      ORIGINS: '*'
      OPENSEARCH_USERNAME: 'opensearch'
      OPENSEARCH_HOST: 'opensearch:9200'
      GRPC_DATASOURCE_HOST: 'openk9-datasource:9000'
      GRPC_TENANT_MANAGER_HOST: 'openk9-tenant-manager:9000'
      GRPC_EMBEDDING_MODULE_HOST: 'openk9-embedding-module:5000'
      KEYCLOAK_URL: 'http://keycloak.openk9.localhost:8081'
      UPLOAD_DIR: 'uploads'
      UPLOAD_FILE_EXTENSIONS: '[".pdf",".md",".docx",".xlsx",".pptx",".csv"]'
      MAX_UPLOAD_FILE_SIZE: '10'
      MAX_UPLOAD_FILES_NUMBER: '5'
  embedding-module:
    image: smclab/openk9-embedding-module-base:${IMAGE_TAG:-2026.1.0-SNAPSHOT}
    container_name: openk9-embedding-module
    hostname: openk9-embedding-module
    environment:
      ORIGINS: '*'
  talk-to:
    image: smclab/openk9-talk-to:${IMAGE_TAG:-2026.1.0-SNAPSHOT}
    container_name: openk9-talk-to
