services:
  rag-module:
    image: ${IMAGE_GROUP:-openk9}/openk9-rag-module:${IMAGE_TAG:-3.0.x-SNAPSHOT}
    container_name: openk9-rag-module
    hostname: openk9-rag-module
    environment:
      ORIGINS: '*'
      OPENSEARCH_USERNAME: 'opensearch'
      OPENSEARCH_HOST: 'opensearch:9200'
      GRPC_DATASOURCE_HOST: 'openk9-datasource:9000'
      GRPC_TENANT_MANAGER_HOST: 'openk9-tenant-manager:9000'
      KEYCLOAK_URL: 'http://keycloak.openk9.localhost:8081'
  embedding-module:
    image: ${IMAGE_GROUP:-openk9}/openk9-embedding-module-base:${IMAGE_TAG:-3.0.x-SNAPSHOT}
    container_name: openk9-embedding-module
    hostname: openk9-embedding-module
    environment:
      ORIGINS: '*'
  talk-to:
    image: ${IMAGE_GROUP:-openk9}/openk9-talk-to:${IMAGE_TAG:-3.0.x-SNAPSHOT}
    container_name: openk9-talk-to
