include:
  - path:
      - compose.yaml

services:
  tenant-manager:
    image: smclab/openk9-tenant-manager:local-dev
  api-gateway:
    image: smclab/openk9-api-gateway:local-dev
  datasource:
    image: smclab/openk9-datasource:local-dev
  ingestion:
    image: smclab/openk9-ingestion:local-dev
  searcher:
    image: smclab/openk9-searcher:local-dev
  search-frontend:
    image: smclab/openk9-search-frontend:local-dev
  admin-ui:
    image: smclab/openk9-admin-ui:local-dev
  tenant-ui:
    image: smclab/openk9-tenant-ui:local-dev
  web-connector:
    image: smclab/openk9-web-connector:local-dev
