FROM python:3.12-slim

RUN mkdir -p /openai_embedding_module  && \
mkdir -p /var/log/openk9
WORKDIR /openai_embedding_module/

COPY app/openai/requirements.openai.txt ./requirements.txt
COPY app/external_services/grpc/embedding/embedding.proto ./

RUN pip install --no-cache-dir -r requirements.txt  && \
python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. embedding.proto

COPY app/text_splitters/derived_text_splitter.py ./
COPY app/utils/text_cleaner.py ./
COPY app/openai/server.openai.py ./server.py
COPY app/openai/client.openai.py ./client.py


EXPOSE 5000

CMD ["python", "server.py"]
