FROM python:3.12-slim

RUN mkdir -p /openai_embedding_module && \
mkdir -p /var/log/openk9
WORKDIR /openai_embedding_module/
COPY ./requirements.openai.txt ./
COPY ./embedding.proto ./
COPY ./derived_text_splitter.py ./
COPY ./server.openai.py ./server.py
COPY ./client.openai.py ./client.py

RUN pip install -r requirements.openai.txt && \
python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. embedding.proto

EXPOSE 5000

CMD ["python", "server.py"]
