# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import searcher_pb2 as app_dot_grpc_dot_searcher__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/grpc/searcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SearcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryParser = channel.unary_unary(
                '/grpc.Searcher/QueryParser',
                request_serializer=app_dot_grpc_dot_searcher__pb2.QueryParserRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_searcher__pb2.QueryParserResponse.FromString,
                _registered_method=True)
        self.SuggestionsQueryParser = channel.unary_unary(
                '/grpc.Searcher/SuggestionsQueryParser',
                request_serializer=app_dot_grpc_dot_searcher__pb2.QueryParserRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_searcher__pb2.SuggestionsResponse.FromString,
                _registered_method=True)
        self.QueryAnalysis = channel.unary_unary(
                '/grpc.Searcher/QueryAnalysis',
                request_serializer=app_dot_grpc_dot_searcher__pb2.QueryAnalysisRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_searcher__pb2.QueryAnalysisResponse.FromString,
                _registered_method=True)


class SearcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryParser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestionsQueryParser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryParser': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryParser,
                    request_deserializer=app_dot_grpc_dot_searcher__pb2.QueryParserRequest.FromString,
                    response_serializer=app_dot_grpc_dot_searcher__pb2.QueryParserResponse.SerializeToString,
            ),
            'SuggestionsQueryParser': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestionsQueryParser,
                    request_deserializer=app_dot_grpc_dot_searcher__pb2.QueryParserRequest.FromString,
                    response_serializer=app_dot_grpc_dot_searcher__pb2.SuggestionsResponse.SerializeToString,
            ),
            'QueryAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAnalysis,
                    request_deserializer=app_dot_grpc_dot_searcher__pb2.QueryAnalysisRequest.FromString,
                    response_serializer=app_dot_grpc_dot_searcher__pb2.QueryAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Searcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.Searcher', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Searcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Searcher/QueryParser',
            app_dot_grpc_dot_searcher__pb2.QueryParserRequest.SerializeToString,
            app_dot_grpc_dot_searcher__pb2.QueryParserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestionsQueryParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Searcher/SuggestionsQueryParser',
            app_dot_grpc_dot_searcher__pb2.QueryParserRequest.SerializeToString,
            app_dot_grpc_dot_searcher__pb2.SuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Searcher/QueryAnalysis',
            app_dot_grpc_dot_searcher__pb2.QueryAnalysisRequest.SerializeToString,
            app_dot_grpc_dot_searcher__pb2.QueryAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
