# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\x1a\x1cgoogle/protobuf/struct.proto\"m\n\x0cRequestChunk\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x14.embedding.ChunkTypeH\x00\x88\x01\x01\x12+\n\njsonConfig\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB\x07\n\x05_type\"M\n\rResponseChunk\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0f\n\x07vectors\x18\x04 \x03(\x02\"j\n\x10\x45mbeddingRequest\x12&\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\x17.embedding.RequestChunk\x12\x14\n\x07\x61pi_key\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04text\x18\x03 \x01(\tB\n\n\x08_api_key\"=\n\x11\x45mbeddingResponse\x12(\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x18.embedding.ResponseChunk*\xaf\x01\n\tChunkType\x12\x16\n\x12\x43HUNK_TYPE_DEFAULT\x10\x00\x12\x1c\n\x18\x43HUNK_TYPE_TEXT_SPLITTER\x10\x01\x12\"\n\x1e\x43HUNK_TYPE_TOKEN_TEXT_SPLITTER\x10\x02\x12&\n\"CHUNK_TYPE_CHARACTER_TEXT_SPLITTER\x10\x03\x12 \n\x1c\x43HUNK_TYPE_SEMANTIC_SPLITTER\x10\x04\x32U\n\tEmbedding\x12H\n\x0bGetMessages\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKTYPE']._serialized_start=422
  _globals['_CHUNKTYPE']._serialized_end=597
  _globals['_REQUESTCHUNK']._serialized_start=60
  _globals['_REQUESTCHUNK']._serialized_end=169
  _globals['_RESPONSECHUNK']._serialized_start=171
  _globals['_RESPONSECHUNK']._serialized_end=248
  _globals['_EMBEDDINGREQUEST']._serialized_start=250
  _globals['_EMBEDDINGREQUEST']._serialized_end=356
  _globals['_EMBEDDINGRESPONSE']._serialized_start=358
  _globals['_EMBEDDINGRESPONSE']._serialized_end=419
  _globals['_EMBEDDING']._serialized_start=599
  _globals['_EMBEDDING']._serialized_end=684
# @@protoc_insertion_point(module_scope)
