/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum ChunkType {
    CHUNK_TYPE_DEFAULT = 'CHUNK_TYPE_DEFAULT',
    CHUNK_TYPE_TEXT_SPLITTER = 'CHUNK_TYPE_TEXT_SPLITTER',
    CHUNK_TYPE_TOKEN_TEXT_SPLITTER = 'CHUNK_TYPE_TOKEN_TEXT_SPLITTER',
    CHUNK_TYPE_CHARACTER_TEXT_SPLITTER = 'CHUNK_TYPE_CHARACTER_TEXT_SPLITTER',
    CHUNK_TYPE_SEMANTIC_SPLITTER = 'CHUNK_TYPE_SEMANTIC_SPLITTER',
    CHUNK_TYPE_SENTENCE_SPLITTER = 'CHUNK_TYPE_SENTENCE_SPLITTER',
    CHUNK_TYPE_RECURSIVE_SPLITTER = 'CHUNK_TYPE_RECURSIVE_SPLITTER',
    CHUNK_TYPE_TABLE_CHUNKER = 'CHUNK_TYPE_TABLE_CHUNKER',
    CHUNK_TYPE_LATE_CHUNKER = 'CHUNK_TYPE_LATE_CHUNKER',
    CHUNK_TYPE_NEURAL_CHUNKER = 'CHUNK_TYPE_NEURAL_CHUNKER',
    UNRECOGNIZED = 'UNRECOGNIZED',
}
