services:
  postgres:
    image: postgres:16
    environment:
    # - ALLOW_EMPTY_PASSWORD is recommended only for development.
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:26.0
    command: start-dev
    depends_on:
      - postgres
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - "./themes/openk9:/opt/keycloak/themes/openk9"

volumes:
  postgres_data:
