apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if (or .Values.commonAnnotations .Values.config.annotations) }}
  annotations: 
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.config.annotations "context" $ ) | nindent 4 }}
  {{- end }}

spec:
  ports:
    - name: hazelcast
      port: 5701
      targetPort: 5701
    - name: http
      port: 8080
      targetPort: 8080
    - name: debug
      port: 5005
      targetPort: 5005
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}

