FROM openjdk:21
WORKDIR /app

COPY  /target/quarkus-app/lib/ ./lib/
COPY  /target/quarkus-app/app/ ./app/
COPY  /target/quarkus-app/quarkus/ ./quarkus/
COPY  /target/quarkus-app/quarkus-run.jar ./quarkus-run.jar

EXPOSE 8080
CMD ["java", "-jar", "quarkus-run.jar"]
