# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/external_services/grpc/tenant_manager/tenant_manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>app/external_services/grpc/tenant_manager/tenant_manager.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"$\n\rTenantRequest\x12\x13\n\x0bvirtualHost\x18\x01 \x01(\t\"B\n\x12TenantListResponse\x12,\n\x0etenantResponse\x18\x01 \x03(\x0b\x32\x14.grpc.TenantResponse\"\x8a\x01\n\x0eTenantResponse\x12\x12\n\nschemaName\x18\x01 \x01(\t\x12\x13\n\x0bvirtualHost\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\x12\x19\n\x0c\x63lientSecret\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x11\n\trealmName\x18\x05 \x01(\tB\x0f\n\r_clientSecret2\x90\x01\n\rTenantManager\x12\x39\n\nFindTenant\x12\x13.grpc.TenantRequest\x1a\x14.grpc.TenantResponse\"\x00\x12\x44\n\x0e\x46indTenantList\x12\x16.google.protobuf.Empty\x1a\x18.grpc.TenantListResponse\"\x00\x42\x34\n\x1cio.openk9.tenantmanager.grpcB\x12TenantManagerProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.external_services.grpc.tenant_manager.tenant_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034io.openk9.tenantmanager.grpcB\022TenantManagerProtoP\001'
  _globals['_TENANTREQUEST']._serialized_start=101
  _globals['_TENANTREQUEST']._serialized_end=137
  _globals['_TENANTLISTRESPONSE']._serialized_start=139
  _globals['_TENANTLISTRESPONSE']._serialized_end=205
  _globals['_TENANTRESPONSE']._serialized_start=208
  _globals['_TENANTRESPONSE']._serialized_end=346
  _globals['_TENANTMANAGER']._serialized_start=349
  _globals['_TENANTMANAGER']._serialized_end=493
# @@protoc_insertion_point(module_scope)
