# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.external_services.grpc.tenant_manager import tenant_manager_pb2 as app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/external_services/grpc/tenant_manager/tenant_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TenantManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindTenant = channel.unary_unary(
                '/grpc.TenantManager/FindTenant',
                request_serializer=app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantRequest.SerializeToString,
                response_deserializer=app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantResponse.FromString,
                _registered_method=True)
        self.FindTenantList = channel.unary_unary(
                '/grpc.TenantManager/FindTenantList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantListResponse.FromString,
                _registered_method=True)


class TenantManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindTenantList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenantManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTenant,
                    request_deserializer=app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantRequest.FromString,
                    response_serializer=app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantResponse.SerializeToString,
            ),
            'FindTenantList': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTenantList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.TenantManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.TenantManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TenantManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TenantManager/FindTenant',
            app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantRequest.SerializeToString,
            app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindTenantList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.TenantManager/FindTenantList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app_dot_external__services_dot_grpc_dot_tenant__manager_dot_tenant__manager__pb2.TenantListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
