# Keycloak Database Setup Job
# Creates keycloak user and database with proper permissions
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db-setup
spec:
  # Auto-delete job after 120 seconds of completion
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: keycloak-db-setup
        image: postgres:18
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          # Create keycloak role if not exists
          psql -tc "SELECT 1 FROM pg_roles WHERE rolname='keycloak'" | grep -q 1 || psql -c "CREATE ROLE keycloak WITH LOGIN ENCRYPTED PASSWORD 'openk9';"
          # Create keycloak database if not exists
          psql -lqt | cut -d \| -f 1 | grep -qw keycloak || psql -c "CREATE DATABASE keycloak OWNER keycloak;"
          # Grant schema permissions
          psql -d keycloak -c "GRANT ALL ON SCHEMA public TO keycloak;"
        env:
        - name: PGHOST
          value: "postgres.test-charts.svc.cluster.local"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: postgres-password
      restartPolicy: Never
