apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: keycloak-db
        image: bitnami/postgresql:14
        command: ["/bin/sh", "-c"]
        args: ["psql -c \"CREATE ROLE keycloak WITH LOGIN ENCRYPTED PASSWORD 'openk9'\"; psql -c \"CREATE DATABASE keycloak OWNER keycloak;\"" ]
        env:
        - name: PGHOST
          value: "postgresql"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: postgres-password
      restartPolicy: Never
