stages:
- push

push-web-connector-helm:
  stage: push
  image: alpine:3.19
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
    changes:
    - connectors/openk9-crawler/chart/**/*
    when: manual
  - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
    when: manual
  # Block the first execution when branch is just created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  before_script:
  - apk update
  - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
  - cd connectors/openk9-crawler/chart/openk9-web-connector && mkdir -p package
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      helm package . -d package --version "$CI_COMMIT_TAG"
    else
      helm package . -d package
    fi
  - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v

push-email-connector-helm:
  stage: push
  image: alpine:3.19
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
    changes:
    - connectors/email-connector/chart/**/*
    when: manual
  - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
    when: manual
  # Block the first execution when branch is just created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  before_script:
  - apk update
  - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
  - cd connectors/email-connector/chart/openk9-email-connector && mkdir -p package
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      helm package . -d package --version "$CI_COMMIT_TAG"
    else
      helm package . -d package
    fi
  - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v

push-database-connector-helm:
  stage: push
  image: alpine:3.19
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
    changes:
    - connectors/database-connector/chart/**/*
    when: manual
  - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
    when: manual
  # Block the first execution when branch is just created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  before_script:
  - apk update
  - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
  - cd connectors/database-connector/chart/openk9-database-connector && mkdir -p package
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      helm package . -d package --version "$CI_COMMIT_TAG"
    else
      helm package . -d package
    fi
  - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v

push-youtube-connector-helm:
  stage: push
  image: alpine:3.19
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
    changes:
    - connectors/youtube-connector/chart/**/*
    when: manual
  - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
    when: manual
  # Block the first execution when branch is just created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  before_script:
  - apk update
  - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
  - cd connectors/youtube-connector/chart/openk9-youtube-connector && mkdir -p package
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      helm package . -d package --version "$CI_COMMIT_TAG"
    else
      helm package . -d package
    fi
  - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v

push-minio-connector-helm:
  stage: push
  image: alpine:3.19
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
    changes:
    - connectors/minio-connector/chart/**/*
    when: manual
  - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
    when: manual
  # Block the first execution when branch is just created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  before_script:
  - apk update
  - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
  - cd connectors/minio-connector/chart/openk9-minio-connector && mkdir -p package
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      helm package . -d package --version "$CI_COMMIT_TAG"
    else
      helm package . -d package
    fi
  - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v

push-gitlab-connector-helm:
  stage: push
  image: alpine:3.19
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
    changes:
    - connectors/gitlab-connector/chart/**/*
    when: manual
  - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
    when: manual
  # Block the first execution when branch is just created
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
    when: never
  before_script:
  - apk update
  - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
  - cd connectors/gitlab-connector/chart/openk9-gitlab-connector && mkdir -p package
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      helm package . -d package --version "$CI_COMMIT_TAG"
    else
      helm package . -d package
    fi
  - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v
