stages:
  - push

push-datasource-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-datasource --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-datasource -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v

push-ingestion-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-ingestion --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-ingestion -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v


push-searcher-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-searcher --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-searcher -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v


push-tenant-manager-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-tenant-manager --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-tenant-manager -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v


push-tenant-ui-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-tenant-ui --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-tenant-ui -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v


push-admin-ui-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-admin-ui --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-admin-ui -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v


push-search-frontend-helm:
  stage: push
  image: alpine:3.19
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH =~ /^\d+\.\d+\.x$/'
      when: manual
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/'
      when: manual
  before_script:
    - apk update
    - apk add --update curl helm && rm -rf /var/cache/apk/*
  script:
    - cd helm-charts/01-base-core && mkdir package
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm package openk9-search-frontend --version "$CI_COMMIT_TAG" -d package
      else
        helm package openk9-search-frontend -d package
      fi
    - curl -u $HELM_REPO_USERNAME:$HELM_REPO_PWD $HELM_REPO_URL --upload-file package/*.tgz -v
