/*
 * Copyright (c) 2020-present SMC Treviso s.r.l. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.openk9.event.tenant;

import java.util.Map;

import lombok.Builder;

/**
 * Defines all the events that would be generated by the producer (the tenant management service).
 */
sealed public interface TenantManagementEvent {

	String TOPIC = "tenant.events";

	/**
	 * Event published when a new tenant is created.
	 *
	 * @param tenantId  the unique identifier of the tenant
	 * @param hostName  the host name associated with the tenant
	 * @param schemaName  the db schema associated with the tenant
	 * @param issuerUri the issuer URI for the tenant’s authentication domain
	 * @param routeAuthorizationMap the mapping of the routes and the authorizationScheme
	 */
	@Builder
	record TenantCreated(
		String tenantId,
		String hostName,
		String schemaName,
		String issuerUri,
		String clientId,
		String clientSecret,
		Map<Route, Authorization> routeAuthorizationMap)
		implements TenantManagementEvent {}

	/**
	 * Event published when a new API key is created for a tenant route.
	 *
	 * @param tenantId   the unique identifier of the tenant
	 * @param apiKeyHash the hashed API key value
	 * @param checksum   the checksum used for API key integrity verification
	 */
	@Builder
	record ApiKeyCreated(String tenantId, String apiKeyHash, String checksum)
		implements TenantManagementEvent {}

	/**
	 * Event published when an existing tenant’s information is updated.
	 *
	 * @param tenantId  the unique identifier of the tenant
	 * @param hostName  the updated host name of the tenant
	 * @param schemaName  the updated db schema associated with the tenant
	 * @param issuerUri the updated issuer URI for the tenant’s authentication domain
	 * @param routeAuthorizationMap the mapping of the routes and the authorizationScheme
	 */
	@Builder
	record TenantUpdated(
		String tenantId,
		String hostName,
		String schemaName,
		String issuerUri,
		String clientId,
		String clientSecret,
		Map<String, String> routeAuthorizationMap)
		implements TenantManagementEvent {}

	/**
	 * Event published when a tenant is deleted.
	 *
	 * @param tenantId the unique identifier of the deleted tenant
	 */
	@Builder
	record TenantDeleted(String tenantId) implements TenantManagementEvent {}

}

