###################### TENANT MANAGER CHILD PIPELINE ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- container-scanning
- restart

Build Tenant-Manager image:
  extends: .build_template
  variables:
    COMPONENT: "tenant-manager"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    # Push image only on main/tag/feature branch - NOT on MR
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]

######################## BUILD VERIFIER ########################
Build Verifier Tenant-Manager:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "tenant-manager"
  rules:
    - !reference [.rules:child-verify-mr, rules]

# SCANNING JOB
Container Scanning Tenant-Manager:
  dependencies: [ Build Tenant-Manager image ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tenant-manager"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]

# RESTART JOB
Trigger Restart Tenant-Manager:
  extends: .restart_job_template
  dependencies:
  - Build Tenant-Manager image
  variables:
    COMPONENT_NAME: "tenant-manager"
    COMPONENT_TYPE: "backend"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]
