###################### K8S-CLIENT CHILD PIPELINE — RELEASE BRANCH ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- restart
- push

Build K8S-Client Release:
  extends: .build_template
  variables:
    COMPONENT: "k8s-client"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic-release, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-release, rules]

Build Verifier K8S-Client:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "k8s-client"
  script:
  - !reference [.maven-build-verifier-logic, script]
  rules:
    - !reference [.rules:child-verify-release-mr, rules]
    - !reference [.rules:child-verify-porting-push, rules]

Trigger Restart K8S-Client Release:
  extends: .restart_job_template
  dependencies:
  - Build K8S-Client Release
  variables:
    COMPONENT_NAME: "k8s-client"
    COMPONENT_TYPE: "backend"
    TARGET_ENV: "k9-stable-2"
  rules:
    - !reference [.rules:child-restart-release, rules]

Copy K8S-Client to DockerHub:
  extends: .skopeo-copy-to-dockerhub
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-k8s-client"
  needs:
    - job: Build K8S-Client Release
      artifacts: true
  rules:
    - !reference [.rules:child-skopeo-release, rules]
