###################### DATASOURCE CHILD PIPELINE ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- container-scanning
- restart

variables:
  CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:7"

# BUILD JOB
Build Datasource image:
  extends: .build_template
  variables:
    COMPONENT: "datasource"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-always, rules]

# SCANNING JOB
Container Scanning Datasource:
  dependencies: [ Build Datasource image ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-datasource"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]

# RESTART JOB
Trigger Restart Datasource:
  extends: .restart_job_template
  dependencies:
  - Build Datasource image
  variables:
    COMPONENT_NAME: "datasource"
    COMPONENT_TYPE: "backend"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]
