###################### TENANT MANAGER CHILD PIPELINE — RELEASE BRANCH ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- container-scanning
- restart
- push

Build Tenant-Manager Release:
  extends: .build_template
  variables:
    COMPONENT: "tenant-manager"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic-release, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-release, rules]

Build Verifier Tenant-Manager:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "tenant-manager"
  script:
  - !reference [.maven-build-verifier-logic, script]
  rules:
    - !reference [.rules:child-verify-release-mr, rules]
    - !reference [.rules:child-verify-porting-push, rules]

Container Scanning Tenant-Manager:
  extends: .container-scanning-template
  needs:
  - job: Build Tenant-Manager Release
    artifacts: true
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tenant-manager"
  rules:
    - !reference [.rules:child-restart-release, rules]

Trigger Restart Tenant-Manager Release:
  extends: .restart_job_template
  dependencies:
  - Build Tenant-Manager Release
  variables:
    COMPONENT_NAME: "tenant-manager"
    COMPONENT_TYPE: "backend"
    TARGET_ENV: "k9-stable-2"
  rules:
    - !reference [.rules:child-restart-release, rules]

Copy Tenant-Manager to DockerHub:
  extends: .skopeo-copy-to-dockerhub
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tenant-manager"
  needs:
    - job: Build Tenant-Manager Release
      artifacts: true
  rules:
    - !reference [.rules:child-skopeo-release, rules]
