###################### K8S-CLIENT CHILD PIPELINE ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- container-scanning
- restart

Build K8S-Client Image:
  extends: .build_template
  variables:
    COMPONENT: "k8s-client"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-always, rules]

# SCANNING JOB
Container Scanning K8S-Client:
  dependencies: [ Build K8S-Client Image ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-k8s-client"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]

# RESTART JOB
Trigger Restart K8S-Client:
  extends: .restart_job_template
  dependencies:
  - Build K8S-Client Image
  variables:
    COMPONENT_NAME: "k8s-client"
    COMPONENT_TYPE: "backend"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]
