###################### FILE MANAGER CHILD PIPELINE ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- container-scanning
- restart

Build File-Manager Image:
  extends: .build_template
  variables:
    COMPONENT: "file-manager"
  stage: build
  script:
  - cd core
  # Clean Maven cache to fix protobuf missing file error (Specific to File Manager)
  - mvn dependency:purge-local-repository -DmanualInclude="io.openk9" -DactOnly=false -DreResolve=false
  - mvn clean
  # Use standard build logic
  - !reference [.maven-build-logic, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    # Push image only on main/tag/feature branch - NOT on MR
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]

######################## BUILD VERIFIER ########################
Build Verifier File-Manager:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "file-manager"
  cache:
    key: "file-manager-mvn"
    paths:
    - $CI_PROJECT_DIR/.m2/repository
    policy: pull
  script:
  # Clean Maven cache also needed for MR verification (same protobuf issue)
  - cd core
  - mvn dependency:purge-local-repository -DmanualInclude="io.openk9" -DactOnly=false -DreResolve=false
  - mvn clean
  - cd ..
  - !reference [.maven-build-verifier-logic, script]
  rules:
    - !reference [.rules:child-verify-mr, rules]

# SCANNING JOB
Container Scanning File-Manager:
  dependencies: [ Build File-Manager Image ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-file-manager"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]

# RESTART JOB
Trigger Restart File-Manager:
  extends: .restart_job_template
  dependencies:
  - Build File-Manager Image
  variables:
    COMPONENT_NAME: "file-manager"
    COMPONENT_TYPE: "backend"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]
