###################### TIKA CHILD PIPELINE — RELEASE BRANCH ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- container-scanning
- restart
- push

Build Tika Release:
  extends: .build_template
  variables:
    COMPONENT: "tika"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic-release, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-release, rules]

Build Verifier Tika:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "tika"
  script:
  - !reference [.maven-build-verifier-logic, script]
  rules:
    - !reference [.rules:child-verify-release-mr, rules]
    - !reference [.rules:child-verify-porting-push, rules]

Container Scanning Tika:
  extends: .container-scanning-template
  needs:
  - job: Build Tika Release
    artifacts: true
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tika"
  rules:
    - !reference [.rules:child-restart-release, rules]

Trigger Restart Tika Release:
  extends: .restart_job_template
  dependencies:
  - Build Tika Release
  variables:
    COMPONENT_NAME: "tika"
    COMPONENT_TYPE: "backend"
    TARGET_ENV: "k9-stable-2"
  rules:
    - !reference [.rules:child-restart-release, rules]

Copy Tika to DockerHub:
  extends: .skopeo-copy-to-dockerhub
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tika"
  needs:
    - job: Build Tika Release
      artifacts: true
  rules:
    - !reference [.rules:child-skopeo-release, rules]
