###################### RESOURCES-VALIDATOR CHILD PIPELINE — RELEASE BRANCH ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- restart
- push

Build Resources-Validator Release:
  extends: .build_template
  variables:
    COMPONENT: "resources-validator"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic-release, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-release, rules]

Build Verifier Resources-Validator:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "resources-validator"
  script:
  - !reference [.maven-build-verifier-logic, script]
  rules:
    - !reference [.rules:child-verify-release-mr, rules]
    - !reference [.rules:child-verify-porting-push, rules]

Trigger Restart Resources-Validator Release:
  extends: .restart_job_template
  dependencies:
  - Build Resources-Validator Release
  variables:
    COMPONENT_NAME: "resources-validator"
    COMPONENT_TYPE: "backend"
    TARGET_ENV: "k9-stable-2"
  rules:
    - !reference [.rules:child-restart-release, rules]

Copy Resources-Validator to DockerHub:
  extends: .skopeo-copy-to-dockerhub
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-resources-validator"
  needs:
    - job: Build Resources-Validator Release
      artifacts: true
  rules:
    - !reference [.rules:child-skopeo-release, rules]
