###################### TIKA CHILD PIPELINE ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- build-verifier
- container-scanning
- restart

Build Tika:
  extends: .build_template
  variables:
    COMPONENT: "tika"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    # main/tag: push versione; designated feature: push snapshot; generic feature: build no push
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]
    - !reference [.rules:child-build-feature-generic, rules]

######################## BUILD VERIFIER ########################
Build Verifier Tika:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "tika"
  rules:
    - !reference [.rules:child-verify-mr, rules]

# SCANNING JOB
Container Scanning Tika:
  dependencies: [ Build Tika ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-tika"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]

# RESTART JOB
Trigger Restart Tika:
  extends: .restart_job_template
  dependencies:
  - Build Tika
  variables:
    COMPONENT_NAME: "tika"
    COMPONENT_TYPE: "backend"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]

# --- RELEASE BRANCH JOBS ---

Build Tika Release:
  extends: .build_template
  variables:
    COMPONENT: "tika"
  stage: build
  script:
  - cd core
  - !reference [.maven-build-logic-release, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-deploy-release, rules]

Build Verifier Tika Release MR:
  extends: .maven-verifier-template
  stage: build-verifier
  variables:
    COMPONENT: "tika"
  script:
  - !reference [.maven-build-verifier-logic, script]
  rules:
    - !reference [.rules:child-verify-release-mr, rules]

Trigger Restart Tika Release:
  extends: .restart_job_template
  dependencies:
  - Build Tika Release
  variables:
    COMPONENT_NAME: "tika"
    COMPONENT_TYPE: "backend"
    TARGET_ENV: "k9-stable-2"
  rules:
    - !reference [.rules:child-deploy-release, rules]
