###################### FILE MANAGER CHILD PIPELINE ######################
include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  - local: '/.gitlab/ci/child-rules.yaml'

stages:
- build
- container-scanning
- restart

Build File-Manager Image:
  extends: .build_template
  variables:
    COMPONENT: "file-manager"
  stage: build
  script:
  - cd core
  # Clean Maven cache to fix protobuf missing file error (Specific to File Manager)
  - mvn dependency:purge-local-repository -DmanualInclude="io.openk9" -DactOnly=false -DreResolve=false
  - mvn clean
  # Use standard build logic
  - !reference [.maven-build-logic, script]
  artifacts:
    paths:
    - .version
    expire_in: 24 hours
  rules:
    - !reference [.rules:child-build-always, rules]

# SCANNING JOB
Container Scanning File-Manager:
  dependencies: [ Build File-Manager Image ]
  extends: .container-scanning-template
  variables:
    REGISTRY_COMPONENT_NAME: "openk9-file-manager"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]

# RESTART JOB
Trigger Restart File-Manager:
  extends: .restart_job_template
  dependencies:
  - Build File-Manager Image
  variables:
    COMPONENT_NAME: "file-manager"
    COMPONENT_TYPE: "backend"
  rules:
    - !reference [.rules:child-deploy-main-tag, rules]
    - !reference [.rules:child-restart-feature, rules]
