#############################################
#            GITLAB CI PIPELINE             #
#        Refactored / Modularized           #
#############################################

stages:
  - trigger
  - build
  - restart
  - quality
  - container-scanning
  - dependency-check
  - build-verifier
  - publish
  - push



include:
  - local: '/.gitlab/.gitlab-templates.yaml'
  
  # 2. Domain-Specific Trigger Files
  - local: '/.gitlab/ci/backend.yaml'
  - local: '/.gitlab/ci/frontend.yaml'
  - local: '/.gitlab/ci/ai.yaml'
  - local: '/.gitlab/ci/common.yaml'
  
  # 3. Global Quality & Security Checks
  - local: '/.gitlab/ci/quality.yaml'
