/*
 * Copyright (c) 2020-present SMC Treviso s.r.l. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.openk9.datasource.web;

import java.util.List;
import java.util.Map;
import java.util.Set;

import io.openk9.datasource.web.dto.openapi.DataIndexDtoExamples;
import jakarta.annotation.security.RolesAllowed;
import jakarta.inject.Inject;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;

import io.openk9.datasource.index.IndexMappingService;
import io.openk9.datasource.index.model.MappingsKey;
import io.openk9.datasource.model.DataIndex;
import io.openk9.datasource.model.dto.base.DataIndexDTO;
import io.openk9.datasource.service.DataIndexService;
import io.openk9.datasource.service.DocTypeService;
import io.openk9.datasource.service.util.K9EntityServiceException;
import io.openk9.datasource.web.dto.DataIndexByDocTypes;

import io.smallrye.mutiny.Uni;
import io.vertx.core.json.JsonObject;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.eclipse.microprofile.faulttolerance.CircuitBreaker;

import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.ExampleObject;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.RequestBody;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

@CircuitBreaker
@Path("/v1/data-index")
@RolesAllowed("k9-admin")
public class DataIndexResource {

	@Inject
	DocTypeService docTypeService;
	@Inject
	DataIndexService dataIndexService;
	@Inject
	IndexMappingService indexMappingService;

	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	public static class AutoGenerateDocTypesRequest {
		private long datasourceId;

	}

	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	public static class GetMappingsOrSettingsFromDocTypesRequest {
		private List<Long> docTypeIds;

	}

	@Operation(operationId = "auto-generate-doc-types")
	@Tag(name = "Auto Generate DocumentTypes API", description = "Permits to generate document types starting from a specific datasource and data index")
	@APIResponses(value = {
			@APIResponse(responseCode = "200", description = "success"),
			@APIResponse(responseCode = "404", description = "not found"),
			@APIResponse(responseCode = "400", description = "invalid"),
			@APIResponse(
					responseCode = "200",
					description = "Auto Generate successful",
					content = {
							@Content(
									mediaType = MediaType.APPLICATION_JSON,
									schema = @Schema(implementation = Response.class),
									example = DataIndexDtoExamples.AUTO_GENERATE_DATA_INDEX_RESPONSE
							)
					}
			),
			@APIResponse(ref = "#/components/responses/bad-request"),
			@APIResponse(ref = "#/components/responses/not-found"),
			@APIResponse(ref = "#/components/responses/internal-server-error"),
	})
	@RequestBody(
			content = {
					@Content(
							mediaType = MediaType.APPLICATION_JSON,
							schema = @Schema(implementation = AutoGenerateDocTypesRequest.class),
							examples = {
									@ExampleObject(
											name = "Auto Generate DTO",
											value = DataIndexDtoExamples.AUTO_GENERATE_DATA_INDEX_DTO
									)
							}
					)
			}
	)
	@Path("/auto-generate-doc-types")
	@POST
	public Uni<Void> autoGenerateDocTypes(
		AutoGenerateDocTypesRequest request) {

		return dataIndexService.autoGenerateDocTypes(request);

	}

	@Operation(operationId = "get-mappings-from-doc-types")
	@Tag(name = "Get Mappings from DocumentTypes API", description = "Get mappings generate from a list of document types.")
	@APIResponses(value = {
			@APIResponse(responseCode = "200", description = "success"),
			@APIResponse(responseCode = "404", description = "not found"),
			@APIResponse(responseCode = "400", description = "invalid"),
			@APIResponse(
					responseCode = "200",
					description = "Get mapping successfully",
					content = {
							@Content(
									mediaType = MediaType.APPLICATION_JSON,
									schema = @Schema(implementation = Response.class),
									example = DataIndexDtoExamples.GET_MAPPINGS_FROM_DOCTYPES_RESPONSE
							)
					}
			),
			@APIResponse(ref = "#/components/responses/bad-request"),
			@APIResponse(ref = "#/components/responses/not-found"),
			@APIResponse(ref = "#/components/responses/internal-server-error"),
	})
	@RequestBody(
			content = {
					@Content(
							mediaType = MediaType.APPLICATION_JSON,
							schema = @Schema(implementation = GetMappingsOrSettingsFromDocTypesRequest.class),
							examples = {
									@ExampleObject(
											name = "Auto Generate DTO",
											value = DataIndexDtoExamples.GET_MAPPINGS_FROM_DOCTYPES_DTO
									)
							}
					)
			}
	)
	@Path("/get-mappings-from-doc-types")
	@POST
	public Uni<Map<MappingsKey, Object>> getMappings(
		GetMappingsOrSettingsFromDocTypesRequest request) {

		return indexMappingService.getMappingsFromDocTypes(request.getDocTypeIds());
	}

	@Operation(operationId = "get-settings-from-doc-types")
	@Tag(name = "Get Settings from DocumentTypes API", description = "Get settings generate from a list of document types.")
	@APIResponses(value = {
			@APIResponse(responseCode = "200", description = "success"),
			@APIResponse(responseCode = "404", description = "not found"),
			@APIResponse(responseCode = "400", description = "invalid"),
			@APIResponse(
					responseCode = "200",
					description = "Get setting successfully",
					content = {
							@Content(
									mediaType = MediaType.APPLICATION_JSON,
									schema = @Schema(implementation = Response.class),
									example = DataIndexDtoExamples.GET_SETTINGS_FROM_DOCTYPES_RESPONSE
							)
					}
			),
			@APIResponse(ref = "#/components/responses/bad-request"),
			@APIResponse(ref = "#/components/responses/not-found"),
			@APIResponse(ref = "#/components/responses/internal-server-error"),
	})
	@RequestBody(
			content = {
					@Content(
							mediaType = MediaType.APPLICATION_JSON,
							schema = @Schema(implementation = GetMappingsOrSettingsFromDocTypesRequest.class),
							examples = {
									@ExampleObject(
											name = "Auto Generate DTO",
											value = DataIndexDtoExamples.GET_SETTINGS_FROM_DOCTYPES_DTO
									)
							}
					)
			}
	)
	@Path("/get-settings-from-doc-types")
	@POST
	public Uni<Map<String, Object>> getSettings(
		GetMappingsOrSettingsFromDocTypesRequest request) {

		return indexMappingService.getSettingsFromDocTypes(request.getDocTypeIds());
	}

	@Path("/create-data-index-from-doc-types/{datasourceId}")
	@POST
	@Deprecated(forRemoval = true)
	public Uni<DataIndex> createDataIndexFromDocTypes(
		@PathParam("datasourceId") long datasourceId,
		DataIndexByDocTypes request) {

		var settings = JsonObject.mapFrom(request.getSettings()).encode();

		DataIndexDTO dataIndexDto = DataIndexDTO.builder()
			.name(request.getIndexName())
			.docTypeIds(Set.copyOf(request.getDocTypeIds()))
			.settings(settings)
			.build();

		return dataIndexService.create(datasourceId, dataIndexDto)
			.map(response -> {
				if (response.getFieldValidators() != null
					&& !response.getFieldValidators().isEmpty()) {

					throw new K9EntityServiceException("An error occurred while creating dataIndex");
				}
				else {
					return response.getEntity();
				}
			});
	}

}
