/*
 * Copyright (c) 2020-present SMC Treviso s.r.l. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.openk9.datasource.web;

import java.time.OffsetDateTime;
import java.util.List;
import jakarta.enterprise.context.control.ActivateRequestContext;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import io.openk9.datasource.listener.SchedulerInitializer;
import io.openk9.datasource.service.SchedulerService;
import io.openk9.datasource.web.dto.TriggerWithDateResourceDTO;
import io.openk9.datasource.web.dto.openapi.SchedulerDtoExamples;

import io.smallrye.mutiny.Uni;
import io.vertx.ext.web.RoutingContext;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.ExampleObject;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.RequestBody;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;

@Path("/v2/trigger")
public class TriggerWithDateResource {

	@Inject
	RoutingContext routingContext;
	@Inject
	Instance<SchedulerInitializer> schedulerInitializer;
	@Inject
	SchedulerService schedulerService;

	/**
	 * Triggers the scheduling or reindexing for the specified datasource and ingestion parameters.
	 * <p>
	 * This method accepts a {@link TriggerV2ResourceDTO} object containing the datasource ID,
	 * reindex flag, and start ingestion date.
	 * It retrieves the status of the schedule that is trying to be started,
	 * and triggers the scheduled jobs if necessary.
	 *
	 * @param dto The {@link TriggerV2ResourceDTO} object containing the parameters for the job trigger.
	 * @return A {@link Uni} representing the status of the triggered job and type of running jobs
	 *         if present as a {@link SchedulerService.TriggerResponse}.
	 */
	@Operation(operationId = "v2-trigger")
	@APIResponses(value = {
			@APIResponse(responseCode = "200", description = "success"),
			@APIResponse(responseCode = "404", description = "not found"),
			@APIResponse(responseCode = "400", description = "invalid"),
			@APIResponse(
					responseCode = "200",
					description = "Auto Generate successful",
					content = {
							@Content(
									mediaType = MediaType.APPLICATION_JSON,
									schema = @Schema(implementation = Response.class),
									example = SchedulerDtoExamples.TRIGGER_RESPONSE
							)
					}
			),
			@APIResponse(ref = "#/components/responses/bad-request"),
			@APIResponse(ref = "#/components/responses/not-found"),
			@APIResponse(ref = "#/components/responses/internal-server-error"),
	})
	@RequestBody(
			content = {
					@Content(
							mediaType = MediaType.APPLICATION_JSON,
							schema = @Schema(implementation = DataIndexResource.AutoGenerateDocTypesRequest.class),
							examples = {
									@ExampleObject(
											name = "Trigger DTO",
											value = SchedulerDtoExamples.TRIGGER_REQUEST
									)
							}
					)
			}
	)
	@POST
	@Consumes(MediaType.APPLICATION_JSON)
	@ActivateRequestContext
	public Uni<SchedulerService.TriggerResponse> trigger(TriggerV2ResourceDTO dto) {

		TriggerWithDateResourceDTO withDateResourceDTO =
			TriggerWithDateResourceDTO.builder()
				.datasourceIds(List.of(dto.getDatasourceId()))
				.reindex(dto.isReindex())
				.startIngestionDate(dto.getStartIngestionDate())
				.build();

		String tenantId = routingContext.get("_tenantId");

		return schedulerService
			.getJobStatus(dto.getDatasourceId())
			.map(jobStatus ->
				schedulerService.checkStartScheduling(jobStatus, dto.isReindex())
			)
			.call(() -> schedulerInitializer
				.get()
				.triggerJobs(tenantId, withDateResourceDTO)
			);
	}

	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	public static class TriggerV2ResourceDTO {
		private long datasourceId;
		private boolean reindex;
		private OffsetDateTime startIngestionDate;
	}
}
