/*
 * Copyright (c) 2020-present SMC Treviso s.r.l. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Compatibility adapter over the @hey-api/openapi-ts generated SDK.
 *
 * It keeps the call-site shape used across the app — `restClient.xxxResource.method(args)`
 * returning the response body directly (throwing on error) — so the migration from
 * the deprecated `openapi-typescript-codegen` did not require touching every call site,
 * and future generator/tag changes are absorbed here instead of rippling across the app.
 */
import { client } from "../openapi-generated/client.gen";
import {
  form,
  getPluginDriversDocumentTypesById,
  getPluginDriversFormById,
  getPluginDriversHealthById,
  getV1ConfigExport,
  health,
  postPluginDriversDocumentTypesById,
  postPluginDriversHealth,
  postSchedulersBySchedulerIdCancelScheduling,
  postSchedulersBySchedulerIdCloseScheduling,
  postSchedulersBySchedulerIdRerouteScheduling,
  postV1DataIndexAutoGenerateDocTypes,
  postV1DataIndexGetMappingsFromDocTypes,
  postV1DataIndexGetSettingsFromDocTypes,
  postV1SearchConfigByIdConfigureHybridSearch,
  postV1Trigger,
  postV2Trigger,
} from "../openapi-generated/sdk.gen";
import type {
  ConfigPackage,
  HybridSearchPipelineDto,
  ImportMode,
  PluginDriverDto,
  PostV1ConfigImportResponses,
  PostV1DataIndexAutoGenerateDocTypesData,
  PostV1DataIndexGetMappingsFromDocTypesData,
  PostV1DataIndexGetSettingsFromDocTypesData,
  ResourceUri,
  TriggerResourceDto,
  TriggerV2ResourceDto,
} from "../openapi-generated/types.gen";
import { getAuthHeaders } from "./authentication";

// The OpenAPI spec paths are relative (e.g. `/schedulers/...`); the backend is served
// behind the `/api/datasource` prefix (see the Vite proxy), so set it as the base URL.
client.setConfig({ baseUrl: "/api/datasource" });

// Inject auth headers on every request (previously done via the client's HEADERS() option).
client.interceptors.request.use(async (request) => {
  const headers = await getAuthHeaders();
  Object.entries(headers).forEach(([key, value]) => request.headers.set(key, value));
  return request;
});

// `throwOnError` makes the SDK throw on non-2xx (as the old client did) and narrows the
// result type so `.data` is always present.
const t = { throwOnError: true } as const;

export const openApiRestClient = {
  formApi: {
    form: (body: ResourceUri) => form({ body, ...t }).then((r) => r.data),
  },
  configResource: {
    exportConfig: () => getV1ConfigExport({ ...t }).then((r) => r.data),
    // The spec does not describe the import request body, so the generated
    // `postV1ConfigImport` types it as `never`. Go through the client directly
    // and keep the package typed here instead.
    importConfig: (body: ConfigPackage, mode: ImportMode) =>
      client
        .post<PostV1ConfigImportResponses, unknown, true>({
          url: "/v1/config/import",
          query: { mode },
          body,
          ...t,
        })
        .then((r) => r.data),
  },
  healthApi: {
    health: (body: ResourceUri) => health({ body, ...t }).then((r) => r.data),
  },
  pluginDriverResource: {
    getApiDatasourcePluginDriversForm: (id: number) =>
      getPluginDriversFormById({ path: { id }, ...t }).then((r) => r.data),
    getApiDatasourcePluginDriversDocumentTypes: (id: number) =>
      getPluginDriversDocumentTypesById({ path: { id }, ...t }).then((r) => r.data),
    postApiDatasourcePluginDriversDocumentTypes: (id: number) =>
      postPluginDriversDocumentTypesById({ path: { id }, ...t }).then((r) => r.data),
    getApiDatasourcePluginDriversHealth: (id: number) =>
      getPluginDriversHealthById({ path: { id }, ...t }).then((r) => r.data),
    postApiDatasourcePluginDriversHealth: (body: PluginDriverDto) =>
      postPluginDriversHealth({ body, ...t }).then((r) => r.data),
  },
  schedulerResource: {
    postApiDatasourceSchedulersCancelScheduling: (schedulerId: number) =>
      postSchedulersBySchedulerIdCancelScheduling({ path: { schedulerId }, ...t }).then((r) => r.data),
    postApiDatasourceSchedulersCloseScheduling: (schedulerId: number) =>
      postSchedulersBySchedulerIdCloseScheduling({ path: { schedulerId }, ...t }).then((r) => r.data),
    postApiDatasourceSchedulersRerouteScheduling: (schedulerId: number) =>
      postSchedulersBySchedulerIdRerouteScheduling({ path: { schedulerId }, ...t }).then((r) => r.data),
  },
  dataIndexResource: {
    postApiDatasourceV1DataIndexGetSettingsFromDocTypes: (
      body: PostV1DataIndexGetSettingsFromDocTypesData["body"],
    ) => postV1DataIndexGetSettingsFromDocTypes({ body, ...t }).then((r) => r.data),
    postApiDatasourceV1DataIndexGetMappingsFromDocTypes: (
      body: PostV1DataIndexGetMappingsFromDocTypesData["body"],
    ) => postV1DataIndexGetMappingsFromDocTypes({ body, ...t }).then((r) => r.data),
    postApiDatasourceV1DataIndexAutoGenerateDocTypes: (
      body: PostV1DataIndexAutoGenerateDocTypesData["body"],
    ) => postV1DataIndexAutoGenerateDocTypes({ body, ...t }).then((r) => r.data),
  },
  searchConfigResource: {
    postApiDatasourceV1SearchConfigConfigureHybridSearch: (id: number, body: HybridSearchPipelineDto) =>
      postV1SearchConfigByIdConfigureHybridSearch({ path: { id }, body, ...t }).then((r) => r.data),
  },
  triggerResource: {
    postApiDatasourceV1Trigger: (body: TriggerResourceDto) => postV1Trigger({ body, ...t }).then((r) => r.data),
  },
  triggerWithDateResource: {
    postApiDatasourceV2Trigger: (body: TriggerV2ResourceDto) => postV2Trigger({ body, ...t }).then((r) => r.data),
  },
};

export type OpenApiRestClient = typeof openApiRestClient;
