version: "3.9"

services:
  # overrides docker-compose.yml web-connector
  web-connector:
    extends:
      file: docker-compose.yml
      service: web-connector
    build:
      args:
        WITH_SCRAPYDWEB: 0
    networks:
      - scrapyd-network

  scrapyd-web:
    build:
      context: .
      dockerfile: /scrapydweb.Dockerfile
    image: scrapyd-web:latest
    environment:
      - SCRAPYDWEB_PORT=5001
      - SCRAPYD_SERVERS=web-connector:6800
    ports:
      # TODO: Check why this does not work
      #- "${SCRAPYDWEB_PORT}:${SCRAPYDWEB_PORT}"
      - 5001:5001  # Same as SCRAPYDWEB_PORT
    depends_on:
      - web-connector
    networks:
      - scrapyd-network


networks:
  scrapyd-network:
    driver: bridge