{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
 {{- if (not (empty .Values.image.pullSecrets)) }}
imagePullSecrets:
  {{- range .Values.image.pullSecrets }}
 - name: {{ . }}
  {{- end }}
 {{- end }}
{{- end }}
