# Example values for production environment
# Usage: helm install api-gateway . -f scenarios/production.yaml

replicaCount: 2

image:
  registry: "registry.smc.it:49083"
  pullPolicy: Always
  pullSecrets:
  - docker-registry-secret

debug:
  enabled: false

database:
  postgresql:
    host: "postgresql.k9-requirements"
    port: 5432

rabbitmq:
  host: "rabbitmq-headless.k9-requirements"
  port: "5672"

openk9:
  searcher:
    host: "openk9-searcher.k9-backend"
    port: "8080"
  datasource:
    host: "openk9-datasource.k9-backend"
    port: "8080"

ingress:
  enabled: true
  host: "openk9.example.com"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: openk9-tls-star-secret

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  averageCpuUtilizationPercentage: 70
  averageMemoryUtilizationPercentage: 80

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus-stack

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - api-gateway
        topologyKey: kubernetes.io/hostname
