// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AutoGenerateDocTypesRequest = {
    datasourceId?: number;
};

export type BehaviorMergeType = 'MERGE' | 'REPLACE';

export type BehaviorOnError = 'SKIP' | 'FAIL' | 'REJECT';

export type Bucket = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    refreshOnSuggestionCategory?: boolean;
    refreshOnTab?: boolean;
    refreshOnDate?: boolean;
    refreshOnQuery?: boolean;
    queryAnalysis?: QueryAnalysis;
    searchConfig?: SearchConfig;
    retrieveType?: RetrieveType;
    enabled?: boolean;
};

export type ChunkType = 'CHUNK_TYPE_DEFAULT' | 'CHUNK_TYPE_TEXT_SPLITTER' | 'CHUNK_TYPE_TOKEN_TEXT_SPLITTER' | 'CHUNK_TYPE_CHARACTER_TEXT_SPLITTER' | 'CHUNK_TYPE_SEMANTIC_SPLITTER' | 'CHUNK_TYPE_SENTENCE_SPLITTER' | 'CHUNK_TYPE_RECURSIVE_SPLITTER' | 'CHUNK_TYPE_TABLE_CHUNKER' | 'CHUNK_TYPE_LATE_CHUNKER' | 'CHUNK_TYPE_NEURAL_CHUNKER' | 'UNRECOGNIZED';

export type CombinationTechnique = 'ARITHMETIC_MEAN' | 'GEOMETRIC_MEAN' | 'ARMONIC_MEAN';

export type DataIndex = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    knnIndex?: boolean;
    chunkType?: ChunkType;
    chunkWindowSize?: number;
    embeddingJsonConfig?: string;
};

export type Datasource = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    description?: string;
    jsonConfig?: string;
    lastIngestionDate?: string;
    name?: string;
    purgeable?: boolean;
    purging?: string;
    purgeMaxAge?: string;
    reindexable?: boolean;
    reindexing?: string;
    schedulable?: boolean;
    scheduling?: string;
};

export type DatasourceJobStatus = {
    id?: number;
    name?: string;
    status?: JobStatus;
};

export type DatasourceMessage = {
    ingestionId?: string;
    datasourceId?: number;
    contentId?: string;
    parsingDate?: number;
    tenantId?: string;
    indexName?: string;
};

export type DocType = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
};

export type DocTypeField = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    floatBoost?: number;
    keyword?: boolean;
    text?: boolean;
    numeric?: boolean;
    date?: boolean;
    boolean?: boolean;
    i18N?: boolean;
    autocomplete?: boolean;
    defaultExclude?: boolean;
    defaultBoost?: boolean;
    searchableAndAutocomplete?: boolean;
    searchableAndDate?: boolean;
    searchableAndText?: boolean;
    searchableAndI18N?: boolean;
    name?: string;
    description?: string;
    fieldName?: string;
    searchable?: boolean;
    sortable?: boolean;
    boost?: number;
    fieldType?: FieldType;
    exclude?: boolean;
    jsonConfig?: string;
    path?: string;
    children?: Array<DocTypeField>;
    docTypeFieldAndChildren?: Array<DocTypeField>;
};

export type DocTypeFieldResponseDto = {
    field?: string;
    id?: number;
    label?: string;
    translationMap?: {
        [key: string]: string;
    };
};

export type DocTypeTemplate = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    templateType?: TemplateType;
    source?: string;
    compiled?: string;
};

export type EnrichItem = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    type?: EnrichItemType;
    resourceUri?: ResourceUri;
    script?: string;
    jsonConfig?: string;
    jsonPath?: string;
    behaviorMergeType?: BehaviorMergeType;
    requestTimeout?: number;
    behaviorOnError?: BehaviorOnError;
};

export type EnrichItemType = 'HTTP_ASYNC' | 'HTTP_SYNC' | 'GROOVY_SCRIPT';

export type EnrichPipeline = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
};

export type EventType = 'CREATE' | 'UPDATE' | 'DELETE';

export type FieldType = 'NULL' | 'BINARY' | 'BOOLEAN' | 'KEYWORD' | 'CONSTANT_KEYWORD' | 'WILDCARD' | 'DATE' | 'DATE_NANOS' | 'LONG' | 'INTEGER' | 'SHORT' | 'BYTE' | 'DOUBLE' | 'FLOAT' | 'HALF_FLOAT' | 'SCALED_FLOAT' | 'UNSIGNED_LONG' | 'OBJECT' | 'FLATTENED' | 'NESTED' | 'JOIN' | 'LONG_RANGE' | 'DOUBLE_RANGE' | 'DATE_RANGE' | 'IP_RANGE' | 'IP' | 'VERSION' | 'MURMUR3' | 'HISTOGRAM' | 'TEXT' | 'ANNOTATED_TEXT' | 'COMPLETION' | 'SEARCH_AS_YOU_TYPE' | 'TOKEN_COUNT' | 'DENSE_VECTOR' | 'KNN_VECTOR' | 'SPARSE_VECTOR' | 'RANK_FEATURE' | 'RANK_FEATURES' | 'GEO_POINT' | 'GEO_SHAPE' | 'POINT' | 'SHAPE' | 'PERCOLATOR' | 'I18N';

export type FieldValue = {
    value?: unknown;
    isDefault?: boolean;
};

export type FormField = {
    info?: string;
    label?: string;
    name?: string;
    type?: FormFieldType;
    size?: number;
    required?: boolean;
    values?: Array<FieldValue>;
    validator?: FormFieldValidator;
};

export type FormFieldType = 'text' | 'number' | 'select' | 'multiselect' | 'list' | 'date' | 'email' | 'password' | 'time' | 'url' | 'checkbox' | 'stringMap';

export type FormFieldValidator = {
    min?: number;
    max?: number;
    regex?: string;
};

export type FormTemplate = {
    fields?: Array<FormField>;
};

export type GetMappingsOrSettingsFromDocTypesRequest = {
    docTypeIds?: Array<number>;
};

export type HealthDto = {
    status: Status;
};

export type HybridSearchPipelineDto = {
    normalizationTechnique?: NormalizationTechnique;
    combinationTechnique?: CombinationTechnique;
    weights?: Array<number>;
};

export type JobStatus = 'TRIGGER_RUNNING' | 'REINDEX_RUNNING' | 'NOT_RUNNING';

export type JsonObject = Array<unknown>;

export type K9Column = 'id' | 'name' | 'description' | 'createDate' | 'modifiedDate';

export type K9EntityEventBucket = {
    type?: EventType;
    entity?: Bucket;
    previousEntity?: Bucket;
};

export type K9EntityEventDataIndex = {
    type?: EventType;
    entity?: DataIndex;
    previousEntity?: DataIndex;
};

export type K9EntityEventDatasource = {
    type?: EventType;
    entity?: Datasource;
    previousEntity?: Datasource;
};

export type K9EntityEventDocType = {
    type?: EventType;
    entity?: DocType;
    previousEntity?: DocType;
};

export type K9EntityEventDocTypeTemplate = {
    type?: EventType;
    entity?: DocTypeTemplate;
    previousEntity?: DocTypeTemplate;
};

export type K9EntityEventEnrichItem = {
    type?: EventType;
    entity?: EnrichItem;
    previousEntity?: EnrichItem;
};

export type K9EntityEventEnrichPipeline = {
    type?: EventType;
    entity?: EnrichPipeline;
    previousEntity?: EnrichPipeline;
};

export type K9EntityEventPluginDriver = {
    type?: EventType;
    entity?: PluginDriver;
    previousEntity?: PluginDriver;
};

export type K9EntityEventSuggestionCategory = {
    type?: EventType;
    entity?: SuggestionCategory;
    previousEntity?: SuggestionCategory;
};

export type NormalizationTechnique = 'MIN_MAX' | 'L2';

export type PageBucket = Array<Bucket>;

export type PageDataIndex = Array<DataIndex>;

export type PageDatasource = Array<Datasource>;

export type PageDocType = Array<DocType>;

export type PageDocTypeField = Array<DocTypeField>;

export type PageDocTypeTemplate = Array<DocTypeTemplate>;

export type PageEnrichItem = Array<EnrichItem>;

export type PageEnrichPipeline = Array<EnrichPipeline>;

export type PagePluginDriver = Array<PluginDriver>;

export type PageSuggestionCategory = Array<SuggestionCategory>;

export type PluginDriver = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    type?: PluginDriverType;
    resourceUri?: ResourceUri;
    provisioning?: Provisioning;
};

export type PluginDriverDto = {
    name: string;
    description?: string;
    type: PluginDriverType;
    provisioning?: Provisioning;
    resourceUri?: ResourceUri;
};

export type PluginDriverDocType = {
    docTypeId?: number;
    name?: string;
    selected?: boolean;
};

export type PluginDriverDocTypesDto = {
    docTypes?: Array<PluginDriverDocType>;
};

export type PluginDriverType = 'HTTP';

/**
 * Problem details for HTTP APIs (rfc7807)
 */
export type Problem = {
    /**
     * An absolute URI that identifies the problem type.
     */
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    /**
     * An absolute URI that identifies the specific occurrence of the problem.
     */
    instance?: string;
};

export type Provisioning = 'SYSTEM' | 'USER';

export type QueryAnalysis = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    stopWords?: string;
    stopWordsList?: Array<string>;
};

export type ResourceUri = {
    baseUri?: string;
    path?: string;
};

export type RetrieveType = 'KNN' | 'HYBRID' | 'TEXT';

export type SchedulingStatus = 'ALLOWED' | 'BLOCKED';

export type SearchConfig = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    minScore?: number;
    minScoreSuggestions?: boolean;
    minScoreSearch?: boolean;
    maxSearchPageFrom?: number;
    maxSearchPageSize?: number;
    maxTextQueryLength?: number;
};

export type SearchPipelineResponseDto = {
    status?: number;
    body?: string;
    reason?: string;
};

export type Status = 'UP' | 'DOWN' | 'UNKNOWN';

export type SuggestionCategory = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    priority?: number;
    multiSelect?: boolean;
};

export type TemplateType = 'JAVASCRIPT_SOURCE' | 'TYPESCRIPT_SOURCE' | 'JAVASCRIPT_COMPILED';

export type TriggerResourceDto = {
    datasourceIds?: Array<number>;
};

export type TriggerResponse = {
    oldJobStatus?: JobStatus;
    status?: SchedulingStatus;
};

export type TriggerV2ResourceDto = {
    datasourceId?: number;
    reindex?: boolean;
    startIngestionDate?: string;
};

export type Tuple2BucketDatasource = {
    left?: Bucket;
    right?: Datasource;
};

export type Tuple2BucketSuggestionCategory = {
    left?: Bucket;
    right?: SuggestionCategory;
};

export type Tuple2DataIndexDocType = {
    left?: DataIndex;
    right?: DocType;
};

export type Tuple2DatasourceDataIndex = {
    left?: Datasource;
    right?: DataIndex;
};

export type Tuple2DatasourceEnrichPipeline = {
    left?: Datasource;
    right?: EnrichPipeline;
};

export type Tuple2DatasourcePluginDriver = {
    left?: Datasource;
    right?: PluginDriver;
};

export type Tuple2DocTypeDocTypeField = {
    left?: DocType;
    right?: DocTypeField;
};

export type Tuple2DocTypeLong = {
    left?: DocType;
    right?: number;
};

export type Tuple2EnrichPipelineEnrichItem = {
    left?: EnrichPipeline;
    right?: EnrichItem;
};

export type Tuple2SuggestionCategoryDocTypeField = {
    left?: SuggestionCategory;
    right?: DocTypeField;
};

export type GetBucketsData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/buckets';
};

export type GetBucketsResponses = {
    /**
     * OK
     */
    200: PageBucket;
};

export type GetBucketsResponse = GetBucketsResponses[keyof GetBucketsResponses];

export type PostBucketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets';
};

export type PostBucketsResponses = {
    /**
     * OK
     */
    200: Bucket;
};

export type PostBucketsResponse = PostBucketsResponses[keyof PostBucketsResponses];

export type GetBucketsCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/count';
};

export type GetBucketsCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetBucketsCountResponse = GetBucketsCountResponses[keyof GetBucketsCountResponses];

export type GetBucketsCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current';
};

export type GetBucketsCurrentErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentError = GetBucketsCurrentErrors[keyof GetBucketsCurrentErrors];

export type GetBucketsCurrentResponses = {
    /**
     * Current Bucket configuration returned
     */
    200: unknown;
};

export type GetBucketsCurrentAvailableLanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/availableLanguage';
};

export type GetBucketsCurrentAvailableLanguageErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentAvailableLanguageError = GetBucketsCurrentAvailableLanguageErrors[keyof GetBucketsCurrentAvailableLanguageErrors];

export type GetBucketsCurrentAvailableLanguageResponses = {
    /**
     * List of available Languages returned
     */
    200: unknown;
};

export type GetBucketsCurrentDefaultLanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/defaultLanguage';
};

export type GetBucketsCurrentDefaultLanguageErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentDefaultLanguageError = GetBucketsCurrentDefaultLanguageErrors[keyof GetBucketsCurrentDefaultLanguageErrors];

export type GetBucketsCurrentDefaultLanguageResponses = {
    /**
     * Default Language returned
     */
    200: unknown;
};

export type GetBucketsCurrentDocTypeFieldsSortableData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/doc-type-fields-sortable';
};

export type GetBucketsCurrentDocTypeFieldsSortableErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentDocTypeFieldsSortableError = GetBucketsCurrentDocTypeFieldsSortableErrors[keyof GetBucketsCurrentDocTypeFieldsSortableErrors];

export type GetBucketsCurrentDocTypeFieldsSortableResponses = {
    /**
     * List of Sortable DocTypeFields returned
     */
    200: unknown;
};

export type GetBucketsCurrentSortingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/sortings';
};

export type GetBucketsCurrentSortingsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentSortingsError = GetBucketsCurrentSortingsErrors[keyof GetBucketsCurrentSortingsErrors];

export type GetBucketsCurrentSortingsResponses = {
    /**
     * List of Sortings returned
     */
    200: unknown;
};

export type GetBucketsCurrentSuggestionCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/suggestionCategories';
};

export type GetBucketsCurrentSuggestionCategoriesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentSuggestionCategoriesError = GetBucketsCurrentSuggestionCategoriesErrors[keyof GetBucketsCurrentSuggestionCategoriesErrors];

export type GetBucketsCurrentSuggestionCategoriesResponses = {
    /**
     * List of Suggestion Categories returned
     */
    200: unknown;
};

export type GetBucketsCurrentTabsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/tabs';
};

export type GetBucketsCurrentTabsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentTabsError = GetBucketsCurrentTabsErrors[keyof GetBucketsCurrentTabsErrors];

export type GetBucketsCurrentTabsResponses = {
    /**
     * List of Tabs returned
     */
    200: unknown;
};

export type GetBucketsCurrentTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/templates';
};

export type GetBucketsCurrentTemplatesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentTemplatesError = GetBucketsCurrentTemplatesErrors[keyof GetBucketsCurrentTemplatesErrors];

export type GetBucketsCurrentTemplatesResponses = {
    /**
     * List of Templates returned
     */
    200: unknown;
};

export type GetBucketsStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/stream';
};

export type GetBucketsStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventBucket>;
};

export type GetBucketsStreamResponse = GetBucketsStreamResponses[keyof GetBucketsStreamResponses];

export type DeleteBucketsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/buckets/{id}';
};

export type DeleteBucketsByIdResponses = {
    /**
     * OK
     */
    200: Bucket;
};

export type DeleteBucketsByIdResponse = DeleteBucketsByIdResponses[keyof DeleteBucketsByIdResponses];

export type GetBucketsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/buckets/{id}';
};

export type GetBucketsByIdResponses = {
    /**
     * OK
     */
    200: Bucket;
};

export type GetBucketsByIdResponse = GetBucketsByIdResponses[keyof GetBucketsByIdResponses];

export type PatchBucketsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/buckets/{id}';
};

export type PatchBucketsByIdResponses = {
    /**
     * OK
     */
    200: Bucket;
};

export type PatchBucketsByIdResponse = PatchBucketsByIdResponses[keyof PatchBucketsByIdResponses];

export type PutBucketsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/buckets/{id}';
};

export type PutBucketsByIdResponses = {
    /**
     * OK
     */
    200: Bucket;
};

export type PutBucketsByIdResponse = PutBucketsByIdResponses[keyof PutBucketsByIdResponses];

export type GetBucketsByIdDatasourcesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/buckets/{id}/datasources';
};

export type GetBucketsByIdDatasourcesResponses = {
    /**
     * OK
     */
    200: PageDatasource;
};

export type GetBucketsByIdDatasourcesResponse = GetBucketsByIdDatasourcesResponses[keyof GetBucketsByIdDatasourcesResponses];

export type DeleteBucketsByIdDatasourcesByDatasourceIdData = {
    body?: never;
    path: {
        datasourceId: number;
        id: number;
    };
    query?: never;
    url: '/buckets/{id}/datasources/{datasourceId}';
};

export type DeleteBucketsByIdDatasourcesByDatasourceIdResponses = {
    /**
     * OK
     */
    200: Tuple2BucketDatasource;
};

export type DeleteBucketsByIdDatasourcesByDatasourceIdResponse = DeleteBucketsByIdDatasourcesByDatasourceIdResponses[keyof DeleteBucketsByIdDatasourcesByDatasourceIdResponses];

export type PutBucketsByIdDatasourcesByDatasourceIdData = {
    body?: never;
    path: {
        datasourceId: number;
        id: number;
    };
    query?: never;
    url: '/buckets/{id}/datasources/{datasourceId}';
};

export type PutBucketsByIdDatasourcesByDatasourceIdResponses = {
    /**
     * OK
     */
    200: Tuple2BucketDatasource;
};

export type PutBucketsByIdDatasourcesByDatasourceIdResponse = PutBucketsByIdDatasourcesByDatasourceIdResponses[keyof PutBucketsByIdDatasourcesByDatasourceIdResponses];

export type GetBucketsByIdSuggestionCategoriesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/buckets/{id}/suggestion-categories';
};

export type GetBucketsByIdSuggestionCategoriesResponses = {
    /**
     * OK
     */
    200: PageSuggestionCategory;
};

export type GetBucketsByIdSuggestionCategoriesResponse = GetBucketsByIdSuggestionCategoriesResponses[keyof GetBucketsByIdSuggestionCategoriesResponses];

export type DeleteBucketsByIdSuggestionCategoriesBySuggestionCategoryIdData = {
    body?: never;
    path: {
        id: number;
        suggestionCategoryId: number;
    };
    query?: never;
    url: '/buckets/{id}/suggestion-categories/{suggestionCategoryId}';
};

export type DeleteBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponses = {
    /**
     * OK
     */
    200: Tuple2BucketSuggestionCategory;
};

export type DeleteBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponse = DeleteBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponses[keyof DeleteBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponses];

export type PutBucketsByIdSuggestionCategoriesBySuggestionCategoryIdData = {
    body?: never;
    path: {
        id: number;
        suggestionCategoryId: number;
    };
    query?: never;
    url: '/buckets/{id}/suggestion-categories/{suggestionCategoryId}';
};

export type PutBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponses = {
    /**
     * OK
     */
    200: Tuple2BucketSuggestionCategory;
};

export type PutBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponse = PutBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponses[keyof PutBucketsByIdSuggestionCategoriesBySuggestionCategoryIdResponses];

export type GetDataIndexesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/data-indexes';
};

export type GetDataIndexesResponses = {
    /**
     * OK
     */
    200: PageDataIndex;
};

export type GetDataIndexesResponse = GetDataIndexesResponses[keyof GetDataIndexesResponses];

export type PostDataIndexesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/data-indexes';
};

export type PostDataIndexesResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type PostDataIndexesResponse = PostDataIndexesResponses[keyof PostDataIndexesResponses];

export type GetDataIndexesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/data-indexes/count';
};

export type GetDataIndexesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetDataIndexesCountResponse = GetDataIndexesCountResponses[keyof GetDataIndexesCountResponses];

export type GetDataIndexesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/data-indexes/stream';
};

export type GetDataIndexesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventDataIndex>;
};

export type GetDataIndexesStreamResponse = GetDataIndexesStreamResponses[keyof GetDataIndexesStreamResponses];

export type DeleteDataIndexesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/data-indexes/{id}';
};

export type DeleteDataIndexesByIdResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type DeleteDataIndexesByIdResponse = DeleteDataIndexesByIdResponses[keyof DeleteDataIndexesByIdResponses];

export type GetDataIndexesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/data-indexes/{id}';
};

export type GetDataIndexesByIdResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type GetDataIndexesByIdResponse = GetDataIndexesByIdResponses[keyof GetDataIndexesByIdResponses];

export type PatchDataIndexesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/data-indexes/{id}';
};

export type PatchDataIndexesByIdResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type PatchDataIndexesByIdResponse = PatchDataIndexesByIdResponses[keyof PatchDataIndexesByIdResponses];

export type PutDataIndexesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/data-indexes/{id}';
};

export type PutDataIndexesByIdResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type PutDataIndexesByIdResponse = PutDataIndexesByIdResponses[keyof PutDataIndexesByIdResponses];

export type GetDataIndexesByIdDocTypesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/data-indexes/{id}/doc-types';
};

export type GetDataIndexesByIdDocTypesResponses = {
    /**
     * OK
     */
    200: PageDocType;
};

export type GetDataIndexesByIdDocTypesResponse = GetDataIndexesByIdDocTypesResponses[keyof GetDataIndexesByIdDocTypesResponses];

export type DeleteDataIndexesByIdDocTypesByDocTypeIdData = {
    body?: never;
    path: {
        docTypeId: number;
        id: number;
    };
    query?: never;
    url: '/data-indexes/{id}/doc-types/{docTypeId}';
};

export type DeleteDataIndexesByIdDocTypesByDocTypeIdResponses = {
    /**
     * OK
     */
    200: Tuple2DataIndexDocType;
};

export type DeleteDataIndexesByIdDocTypesByDocTypeIdResponse = DeleteDataIndexesByIdDocTypesByDocTypeIdResponses[keyof DeleteDataIndexesByIdDocTypesByDocTypeIdResponses];

export type PutDataIndexesByIdDocTypesByDocTypeIdData = {
    body?: never;
    path: {
        docTypeId: number;
        id: number;
    };
    query?: never;
    url: '/data-indexes/{id}/doc-types/{docTypeId}';
};

export type PutDataIndexesByIdDocTypesByDocTypeIdResponses = {
    /**
     * OK
     */
    200: Tuple2DataIndexDocType;
};

export type PutDataIndexesByIdDocTypesByDocTypeIdResponse = PutDataIndexesByIdDocTypesByDocTypeIdResponses[keyof PutDataIndexesByIdDocTypesByDocTypeIdResponses];

export type GetDatasourceEventData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasource-event';
};

export type GetDatasourceEventResponses = {
    /**
     * OK
     */
    200: Array<DatasourceMessage>;
};

export type GetDatasourceEventResponse = GetDatasourceEventResponses[keyof GetDatasourceEventResponses];

export type GetDatasourcesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/datasources';
};

export type GetDatasourcesResponses = {
    /**
     * OK
     */
    200: PageDatasource;
};

export type GetDatasourcesResponse = GetDatasourcesResponses[keyof GetDatasourcesResponses];

export type PostDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources';
};

export type PostDatasourcesResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type PostDatasourcesResponse = PostDatasourcesResponses[keyof PostDatasourcesResponses];

export type GetDatasourcesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/count';
};

export type GetDatasourcesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetDatasourcesCountResponse = GetDatasourcesCountResponses[keyof GetDatasourcesCountResponses];

export type GetDatasourcesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datasources/stream';
};

export type GetDatasourcesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventDatasource>;
};

export type GetDatasourcesStreamResponse = GetDatasourcesStreamResponses[keyof GetDatasourcesStreamResponses];

export type DeleteDatasourcesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}';
};

export type DeleteDatasourcesByIdResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type DeleteDatasourcesByIdResponse = DeleteDatasourcesByIdResponses[keyof DeleteDatasourcesByIdResponses];

export type GetDatasourcesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}';
};

export type GetDatasourcesByIdResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type GetDatasourcesByIdResponse = GetDatasourcesByIdResponses[keyof GetDatasourcesByIdResponses];

export type PatchDatasourcesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}';
};

export type PatchDatasourcesByIdResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type PatchDatasourcesByIdResponse = PatchDatasourcesByIdResponses[keyof PatchDatasourcesByIdResponses];

export type PutDatasourcesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}';
};

export type PutDatasourcesByIdResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type PutDatasourcesByIdResponse = PutDatasourcesByIdResponses[keyof PutDatasourcesByIdResponses];

export type DeleteDatasourcesByIdDataIndexData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/data-index';
};

export type DeleteDatasourcesByIdDataIndexResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type DeleteDatasourcesByIdDataIndexResponse = DeleteDatasourcesByIdDataIndexResponses[keyof DeleteDatasourcesByIdDataIndexResponses];

export type GetDatasourcesByIdDataIndexOrphansData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/data-index-orphans';
};

export type GetDatasourcesByIdDataIndexOrphansResponses = {
    /**
     * OK
     */
    200: Array<DataIndex>;
};

export type GetDatasourcesByIdDataIndexOrphansResponse = GetDatasourcesByIdDataIndexOrphansResponses[keyof GetDatasourcesByIdDataIndexOrphansResponses];

export type GetDatasourcesByIdDataIndexByDataIndexIdData = {
    body?: never;
    path: {
        dataIndexId: number;
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/data-index/{dataIndexId}';
};

export type GetDatasourcesByIdDataIndexByDataIndexIdResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type GetDatasourcesByIdDataIndexByDataIndexIdResponse = GetDatasourcesByIdDataIndexByDataIndexIdResponses[keyof GetDatasourcesByIdDataIndexByDataIndexIdResponses];

export type PutDatasourcesByIdDataIndexByDataIndexIdData = {
    body?: never;
    path: {
        dataIndexId: number;
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/data-index/{dataIndexId}';
};

export type PutDatasourcesByIdDataIndexByDataIndexIdResponses = {
    /**
     * OK
     */
    200: Tuple2DatasourceDataIndex;
};

export type PutDatasourcesByIdDataIndexByDataIndexIdResponse = PutDatasourcesByIdDataIndexByDataIndexIdResponses[keyof PutDatasourcesByIdDataIndexByDataIndexIdResponses];

export type DeleteDatasourcesByIdEnrichPipelineData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/enrich-pipeline';
};

export type DeleteDatasourcesByIdEnrichPipelineResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type DeleteDatasourcesByIdEnrichPipelineResponse = DeleteDatasourcesByIdEnrichPipelineResponses[keyof DeleteDatasourcesByIdEnrichPipelineResponses];

export type GetDatasourcesByIdEnrichPipelineData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/enrich-pipeline';
};

export type GetDatasourcesByIdEnrichPipelineResponses = {
    /**
     * OK
     */
    200: EnrichPipeline;
};

export type GetDatasourcesByIdEnrichPipelineResponse = GetDatasourcesByIdEnrichPipelineResponses[keyof GetDatasourcesByIdEnrichPipelineResponses];

export type PutDatasourcesByIdEnrichPipelineByEnrichPipelineIdData = {
    body?: never;
    path: {
        enrichPipelineId: number;
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/enrich-pipeline/{enrichPipelineId}';
};

export type PutDatasourcesByIdEnrichPipelineByEnrichPipelineIdResponses = {
    /**
     * OK
     */
    200: Tuple2DatasourceEnrichPipeline;
};

export type PutDatasourcesByIdEnrichPipelineByEnrichPipelineIdResponse = PutDatasourcesByIdEnrichPipelineByEnrichPipelineIdResponses[keyof PutDatasourcesByIdEnrichPipelineByEnrichPipelineIdResponses];

export type DeleteDatasourcesByIdPluginDriverData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/plugin-driver';
};

export type DeleteDatasourcesByIdPluginDriverResponses = {
    /**
     * OK
     */
    200: Datasource;
};

export type DeleteDatasourcesByIdPluginDriverResponse = DeleteDatasourcesByIdPluginDriverResponses[keyof DeleteDatasourcesByIdPluginDriverResponses];

export type GetDatasourcesByIdPluginDriverData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/datasources/{id}/plugin-driver';
};

export type GetDatasourcesByIdPluginDriverResponses = {
    /**
     * OK
     */
    200: PluginDriver;
};

export type GetDatasourcesByIdPluginDriverResponse = GetDatasourcesByIdPluginDriverResponses[keyof GetDatasourcesByIdPluginDriverResponses];

export type PutDatasourcesByIdPluginDriverByPluginDriverIdData = {
    body?: never;
    path: {
        id: number;
        pluginDriverId: number;
    };
    query?: never;
    url: '/datasources/{id}/plugin-driver/{pluginDriverId}';
};

export type PutDatasourcesByIdPluginDriverByPluginDriverIdResponses = {
    /**
     * OK
     */
    200: Tuple2DatasourcePluginDriver;
};

export type PutDatasourcesByIdPluginDriverByPluginDriverIdResponse = PutDatasourcesByIdPluginDriverByPluginDriverIdResponses[keyof PutDatasourcesByIdPluginDriverByPluginDriverIdResponses];

export type GetDocTypesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/doc-types';
};

export type GetDocTypesResponses = {
    /**
     * OK
     */
    200: PageDocType;
};

export type GetDocTypesResponse = GetDocTypesResponses[keyof GetDocTypesResponses];

export type PostDocTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc-types';
};

export type PostDocTypesResponses = {
    /**
     * OK
     */
    200: DocType;
};

export type PostDocTypesResponse = PostDocTypesResponses[keyof PostDocTypesResponses];

export type GetDocTypesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc-types/count';
};

export type GetDocTypesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetDocTypesCountResponse = GetDocTypesCountResponses[keyof GetDocTypesCountResponses];

export type GetDocTypesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc-types/stream';
};

export type GetDocTypesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventDocType>;
};

export type GetDocTypesStreamResponse = GetDocTypesStreamResponses[keyof GetDocTypesStreamResponses];

export type DeleteDocTypesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc-types/{id}';
};

export type DeleteDocTypesByIdResponses = {
    /**
     * OK
     */
    200: DocType;
};

export type DeleteDocTypesByIdResponse = DeleteDocTypesByIdResponses[keyof DeleteDocTypesByIdResponses];

export type GetDocTypesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc-types/{id}';
};

export type GetDocTypesByIdResponses = {
    /**
     * OK
     */
    200: DocType;
};

export type GetDocTypesByIdResponse = GetDocTypesByIdResponses[keyof GetDocTypesByIdResponses];

export type PatchDocTypesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc-types/{id}';
};

export type PatchDocTypesByIdResponses = {
    /**
     * OK
     */
    200: DocType;
};

export type PatchDocTypesByIdResponse = PatchDocTypesByIdResponses[keyof PatchDocTypesByIdResponses];

export type PutDocTypesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc-types/{id}';
};

export type PutDocTypesByIdResponses = {
    /**
     * OK
     */
    200: DocType;
};

export type PutDocTypesByIdResponse = PutDocTypesByIdResponses[keyof PutDocTypesByIdResponses];

export type GetDocTypesByIdDocTypeFieldsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/doc-types/{id}/doc-type-fields';
};

export type GetDocTypesByIdDocTypeFieldsResponses = {
    /**
     * OK
     */
    200: PageDocTypeField;
};

export type GetDocTypesByIdDocTypeFieldsResponse = GetDocTypesByIdDocTypeFieldsResponses[keyof GetDocTypesByIdDocTypeFieldsResponses];

export type PutDocTypesByIdDocTypeFieldsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc-types/{id}/doc-type-fields';
};

export type PutDocTypesByIdDocTypeFieldsResponses = {
    /**
     * OK
     */
    200: Tuple2DocTypeDocTypeField;
};

export type PutDocTypesByIdDocTypeFieldsResponse = PutDocTypesByIdDocTypeFieldsResponses[keyof PutDocTypesByIdDocTypeFieldsResponses];

export type DeleteDocTypesByIdDocTypeFieldsByDocTypeFieldIdData = {
    body?: never;
    path: {
        docTypeFieldId: number;
        id: number;
    };
    query?: never;
    url: '/doc-types/{id}/doc-type-fields/{docTypeFieldId}';
};

export type DeleteDocTypesByIdDocTypeFieldsByDocTypeFieldIdResponses = {
    /**
     * OK
     */
    200: Tuple2DocTypeLong;
};

export type DeleteDocTypesByIdDocTypeFieldsByDocTypeFieldIdResponse = DeleteDocTypesByIdDocTypeFieldsByDocTypeFieldIdResponses[keyof DeleteDocTypesByIdDocTypeFieldsByDocTypeFieldIdResponses];

export type GetEnrichItemsData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/enrich-items';
};

export type GetEnrichItemsResponses = {
    /**
     * OK
     */
    200: PageEnrichItem;
};

export type GetEnrichItemsResponse = GetEnrichItemsResponses[keyof GetEnrichItemsResponses];

export type PostEnrichItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/enrich-items';
};

export type PostEnrichItemsResponses = {
    /**
     * OK
     */
    200: EnrichItem;
};

export type PostEnrichItemsResponse = PostEnrichItemsResponses[keyof PostEnrichItemsResponses];

export type GetEnrichItemsCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/enrich-items/count';
};

export type GetEnrichItemsCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetEnrichItemsCountResponse = GetEnrichItemsCountResponses[keyof GetEnrichItemsCountResponses];

export type GetEnrichItemsStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/enrich-items/stream';
};

export type GetEnrichItemsStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventEnrichItem>;
};

export type GetEnrichItemsStreamResponse = GetEnrichItemsStreamResponses[keyof GetEnrichItemsStreamResponses];

export type DeleteEnrichItemsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-items/{id}';
};

export type DeleteEnrichItemsByIdResponses = {
    /**
     * OK
     */
    200: EnrichItem;
};

export type DeleteEnrichItemsByIdResponse = DeleteEnrichItemsByIdResponses[keyof DeleteEnrichItemsByIdResponses];

export type GetEnrichItemsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-items/{id}';
};

export type GetEnrichItemsByIdResponses = {
    /**
     * OK
     */
    200: EnrichItem;
};

export type GetEnrichItemsByIdResponse = GetEnrichItemsByIdResponses[keyof GetEnrichItemsByIdResponses];

export type PatchEnrichItemsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-items/{id}';
};

export type PatchEnrichItemsByIdResponses = {
    /**
     * OK
     */
    200: EnrichItem;
};

export type PatchEnrichItemsByIdResponse = PatchEnrichItemsByIdResponses[keyof PatchEnrichItemsByIdResponses];

export type PutEnrichItemsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-items/{id}';
};

export type PutEnrichItemsByIdResponses = {
    /**
     * OK
     */
    200: EnrichItem;
};

export type PutEnrichItemsByIdResponse = PutEnrichItemsByIdResponses[keyof PutEnrichItemsByIdResponses];

export type GetEnrichPipelinesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/enrich-pipelines';
};

export type GetEnrichPipelinesResponses = {
    /**
     * OK
     */
    200: PageEnrichPipeline;
};

export type GetEnrichPipelinesResponse = GetEnrichPipelinesResponses[keyof GetEnrichPipelinesResponses];

export type PostEnrichPipelinesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/enrich-pipelines';
};

export type PostEnrichPipelinesResponses = {
    /**
     * OK
     */
    200: EnrichPipeline;
};

export type PostEnrichPipelinesResponse = PostEnrichPipelinesResponses[keyof PostEnrichPipelinesResponses];

export type GetEnrichPipelinesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/enrich-pipelines/count';
};

export type GetEnrichPipelinesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetEnrichPipelinesCountResponse = GetEnrichPipelinesCountResponses[keyof GetEnrichPipelinesCountResponses];

export type GetEnrichPipelinesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/enrich-pipelines/stream';
};

export type GetEnrichPipelinesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventEnrichPipeline>;
};

export type GetEnrichPipelinesStreamResponse = GetEnrichPipelinesStreamResponses[keyof GetEnrichPipelinesStreamResponses];

export type DeleteEnrichPipelinesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-pipelines/{id}';
};

export type DeleteEnrichPipelinesByIdResponses = {
    /**
     * OK
     */
    200: EnrichPipeline;
};

export type DeleteEnrichPipelinesByIdResponse = DeleteEnrichPipelinesByIdResponses[keyof DeleteEnrichPipelinesByIdResponses];

export type GetEnrichPipelinesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-pipelines/{id}';
};

export type GetEnrichPipelinesByIdResponses = {
    /**
     * OK
     */
    200: EnrichPipeline;
};

export type GetEnrichPipelinesByIdResponse = GetEnrichPipelinesByIdResponses[keyof GetEnrichPipelinesByIdResponses];

export type PatchEnrichPipelinesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-pipelines/{id}';
};

export type PatchEnrichPipelinesByIdResponses = {
    /**
     * OK
     */
    200: EnrichPipeline;
};

export type PatchEnrichPipelinesByIdResponse = PatchEnrichPipelinesByIdResponses[keyof PatchEnrichPipelinesByIdResponses];

export type PutEnrichPipelinesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/enrich-pipelines/{id}';
};

export type PutEnrichPipelinesByIdResponses = {
    /**
     * OK
     */
    200: EnrichPipeline;
};

export type PutEnrichPipelinesByIdResponse = PutEnrichPipelinesByIdResponses[keyof PutEnrichPipelinesByIdResponses];

export type GetEnrichPipelinesByIdEnrichItemsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/enrich-pipelines/{id}/enrich-items';
};

export type GetEnrichPipelinesByIdEnrichItemsResponses = {
    /**
     * OK
     */
    200: PageEnrichItem;
};

export type GetEnrichPipelinesByIdEnrichItemsResponse = GetEnrichPipelinesByIdEnrichItemsResponses[keyof GetEnrichPipelinesByIdEnrichItemsResponses];

export type DeleteEnrichPipelinesByIdEnrichItemsByEnrichItemIdData = {
    body?: never;
    path: {
        enrichItemId: number;
        id: number;
    };
    query?: never;
    url: '/enrich-pipelines/{id}/enrich-items/{enrichItemId}';
};

export type DeleteEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponses = {
    /**
     * OK
     */
    200: Tuple2EnrichPipelineEnrichItem;
};

export type DeleteEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponse = DeleteEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponses[keyof DeleteEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponses];

export type PutEnrichPipelinesByIdEnrichItemsByEnrichItemIdData = {
    body?: never;
    path: {
        enrichItemId: number;
        id: number;
    };
    query?: {
        tail?: boolean;
    };
    url: '/enrich-pipelines/{id}/enrich-items/{enrichItemId}';
};

export type PutEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponses = {
    /**
     * OK
     */
    200: Tuple2EnrichPipelineEnrichItem;
};

export type PutEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponse = PutEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponses[keyof PutEnrichPipelinesByIdEnrichItemsByEnrichItemIdResponses];

export type FormData = {
    body: ResourceUri;
    path?: never;
    query?: never;
    url: '/enrichers/form';
};

export type FormErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * The service does not expose a form endpoint or returned an invalid response
     */
    502: Problem;
};

export type FormError = FormErrors[keyof FormErrors];

export type FormResponses = {
    /**
     * Form returned
     */
    200: unknown;
};

export type HealthData = {
    body: ResourceUri;
    path?: never;
    query?: never;
    url: '/enrichers/health';
};

export type HealthErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * Health Check Ok
     */
    200: unknown;
};

export type PostPipelineCallbackByTokenIdData = {
    body?: never;
    path: {
        'token-id': string;
    };
    query?: never;
    url: '/pipeline/callback/{token-id}';
};

export type PostPipelineCallbackByTokenIdResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostPipelineEnrichItemByEnrichItemIdData = {
    body?: never;
    path: {
        'enrich-item-id': number;
    };
    query?: never;
    url: '/pipeline/enrich-item/{enrich-item-id}';
};

export type PostPipelineEnrichItemByEnrichItemIdResponses = {
    /**
     * OK
     */
    200: JsonObject;
};

export type PostPipelineEnrichItemByEnrichItemIdResponse = PostPipelineEnrichItemByEnrichItemIdResponses[keyof PostPipelineEnrichItemByEnrichItemIdResponses];

export type GetPluginDriversData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/plugin-drivers';
};

export type GetPluginDriversResponses = {
    /**
     * OK
     */
    200: PagePluginDriver;
};

export type GetPluginDriversResponse = GetPluginDriversResponses[keyof GetPluginDriversResponses];

export type PostPluginDriversData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plugin-drivers';
};

export type PostPluginDriversResponses = {
    /**
     * OK
     */
    200: PluginDriver;
};

export type PostPluginDriversResponse = PostPluginDriversResponses[keyof PostPluginDriversResponses];

export type GetPluginDriversCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plugin-drivers/count';
};

export type GetPluginDriversCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetPluginDriversCountResponse = GetPluginDriversCountResponses[keyof GetPluginDriversCountResponses];

export type GetPluginDriversStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plugin-drivers/stream';
};

export type GetPluginDriversStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventPluginDriver>;
};

export type GetPluginDriversStreamResponse = GetPluginDriversStreamResponses[keyof GetPluginDriversStreamResponses];

export type DeletePluginDriversByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/plugin-drivers/{id}';
};

export type DeletePluginDriversByIdResponses = {
    /**
     * OK
     */
    200: PluginDriver;
};

export type DeletePluginDriversByIdResponse = DeletePluginDriversByIdResponses[keyof DeletePluginDriversByIdResponses];

export type GetPluginDriversByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/plugin-drivers/{id}';
};

export type GetPluginDriversByIdResponses = {
    /**
     * OK
     */
    200: PluginDriver;
};

export type GetPluginDriversByIdResponse = GetPluginDriversByIdResponses[keyof GetPluginDriversByIdResponses];

export type PatchPluginDriversByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/plugin-drivers/{id}';
};

export type PatchPluginDriversByIdResponses = {
    /**
     * OK
     */
    200: PluginDriver;
};

export type PatchPluginDriversByIdResponse = PatchPluginDriversByIdResponses[keyof PatchPluginDriversByIdResponses];

export type PutPluginDriversByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/plugin-drivers/{id}';
};

export type PutPluginDriversByIdResponses = {
    /**
     * OK
     */
    200: PluginDriver;
};

export type PutPluginDriversByIdResponse = PutPluginDriversByIdResponses[keyof PutPluginDriversByIdResponses];

export type GetPluginDriversDocumentTypesByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/documentTypes/{id}';
};

export type GetPluginDriversDocumentTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetPluginDriversDocumentTypesByIdError = GetPluginDriversDocumentTypesByIdErrors[keyof GetPluginDriversDocumentTypesByIdErrors];

export type GetPluginDriversDocumentTypesByIdResponses = {
    /**
     * The list of the Document Types created from this Plugin Driver
     */
    200: PluginDriverDocTypesDto;
};

export type GetPluginDriversDocumentTypesByIdResponse = GetPluginDriversDocumentTypesByIdResponses[keyof GetPluginDriversDocumentTypesByIdResponses];

export type PostPluginDriversDocumentTypesByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/documentTypes/{id}';
};

export type PostPluginDriversDocumentTypesByIdResponses = {
    /**
     * OK
     */
    200: Array<DocType>;
};

export type PostPluginDriversDocumentTypesByIdResponse = PostPluginDriversDocumentTypesByIdResponses[keyof PostPluginDriversDocumentTypesByIdResponses];

export type GetPluginDriversFormByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/form/{id}';
};

export type GetPluginDriversFormByIdErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * The service does not expose a form endpoint or returned an invalid response
     */
    502: Problem;
};

export type GetPluginDriversFormByIdError = GetPluginDriversFormByIdErrors[keyof GetPluginDriversFormByIdErrors];

export type GetPluginDriversFormByIdResponses = {
    /**
     * Form returned
     */
    200: FormTemplate;
};

export type GetPluginDriversFormByIdResponse = GetPluginDriversFormByIdResponses[keyof GetPluginDriversFormByIdResponses];

export type PostPluginDriversHealthData = {
    body: PluginDriverDto;
    path?: never;
    query?: never;
    url: '/pluginDrivers/health';
};

export type PostPluginDriversHealthErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostPluginDriversHealthError = PostPluginDriversHealthErrors[keyof PostPluginDriversHealthErrors];

export type PostPluginDriversHealthResponses = {
    /**
     * Plugin Driver Health Status
     */
    200: HealthDto;
};

export type PostPluginDriversHealthResponse = PostPluginDriversHealthResponses[keyof PostPluginDriversHealthResponses];

export type GetPluginDriversHealthByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/health/{id}';
};

export type GetPluginDriversHealthByIdErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetPluginDriversHealthByIdError = GetPluginDriversHealthByIdErrors[keyof GetPluginDriversHealthByIdErrors];

export type GetPluginDriversHealthByIdResponses = {
    /**
     * Plugin Driver Health Status
     */
    200: HealthDto;
};

export type GetPluginDriversHealthByIdResponse = GetPluginDriversHealthByIdResponses[keyof GetPluginDriversHealthByIdResponses];

export type GetSchedulersStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schedulers/status';
};

export type GetSchedulersStatusErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetSchedulersStatusError = GetSchedulersStatusErrors[keyof GetSchedulersStatusErrors];

export type GetSchedulersStatusResponses = {
    /**
     * Health statud for each scheduled Datasource Indexing Job.
     */
    200: unknown;
};

export type PostSchedulersBySchedulerIdCancelSchedulingData = {
    body?: never;
    path: {
        /**
         * Scheduler entity ID
         */
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/cancelScheduling';
};

export type PostSchedulersBySchedulerIdCancelSchedulingErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostSchedulersBySchedulerIdCancelSchedulingError = PostSchedulersBySchedulerIdCancelSchedulingErrors[keyof PostSchedulersBySchedulerIdCancelSchedulingErrors];

export type PostSchedulersBySchedulerIdCancelSchedulingResponses = {
    /**
     * Scheduling cancelled
     */
    204: void;
};

export type PostSchedulersBySchedulerIdCancelSchedulingResponse = PostSchedulersBySchedulerIdCancelSchedulingResponses[keyof PostSchedulersBySchedulerIdCancelSchedulingResponses];

export type PostSchedulersBySchedulerIdCloseSchedulingData = {
    body?: never;
    path: {
        /**
         * Scheduler entity ID
         */
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/closeScheduling';
};

export type PostSchedulersBySchedulerIdCloseSchedulingErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostSchedulersBySchedulerIdCloseSchedulingError = PostSchedulersBySchedulerIdCloseSchedulingErrors[keyof PostSchedulersBySchedulerIdCloseSchedulingErrors];

export type PostSchedulersBySchedulerIdCloseSchedulingResponses = {
    /**
     * Scheduling closed
     */
    204: void;
};

export type PostSchedulersBySchedulerIdCloseSchedulingResponse = PostSchedulersBySchedulerIdCloseSchedulingResponses[keyof PostSchedulersBySchedulerIdCloseSchedulingResponses];

export type GetSchedulersBySchedulerIdGetDeletedContentIdsData = {
    body?: never;
    path: {
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/getDeletedContentIds';
};

export type GetSchedulersBySchedulerIdGetDeletedContentIdsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetSchedulersBySchedulerIdGetDeletedContentIdsError = GetSchedulersBySchedulerIdGetDeletedContentIdsErrors[keyof GetSchedulersBySchedulerIdGetDeletedContentIdsErrors];

export type GetSchedulersBySchedulerIdGetDeletedContentIdsResponses = {
    /**
     * List of deleted content ids returned
     */
    200: Array<unknown>;
};

export type GetSchedulersBySchedulerIdGetDeletedContentIdsResponse = GetSchedulersBySchedulerIdGetDeletedContentIdsResponses[keyof GetSchedulersBySchedulerIdGetDeletedContentIdsResponses];

export type PostSchedulersBySchedulerIdRerouteSchedulingData = {
    body?: never;
    path: {
        /**
         * Scheduler entity ID
         */
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/rerouteScheduling';
};

export type PostSchedulersBySchedulerIdRerouteSchedulingErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostSchedulersBySchedulerIdRerouteSchedulingError = PostSchedulersBySchedulerIdRerouteSchedulingErrors[keyof PostSchedulersBySchedulerIdRerouteSchedulingErrors];

export type PostSchedulersBySchedulerIdRerouteSchedulingResponses = {
    /**
     * Scheduling rerouted successfully
     */
    204: void;
};

export type PostSchedulersBySchedulerIdRerouteSchedulingResponse = PostSchedulersBySchedulerIdRerouteSchedulingResponses[keyof PostSchedulersBySchedulerIdRerouteSchedulingResponses];

export type GetSuggestionCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/suggestion-categories';
};

export type GetSuggestionCategoriesResponses = {
    /**
     * OK
     */
    200: PageSuggestionCategory;
};

export type GetSuggestionCategoriesResponse = GetSuggestionCategoriesResponses[keyof GetSuggestionCategoriesResponses];

export type PostSuggestionCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/suggestion-categories';
};

export type PostSuggestionCategoriesResponses = {
    /**
     * OK
     */
    200: SuggestionCategory;
};

export type PostSuggestionCategoriesResponse = PostSuggestionCategoriesResponses[keyof PostSuggestionCategoriesResponses];

export type GetSuggestionCategoriesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/suggestion-categories/count';
};

export type GetSuggestionCategoriesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetSuggestionCategoriesCountResponse = GetSuggestionCategoriesCountResponses[keyof GetSuggestionCategoriesCountResponses];

export type GetSuggestionCategoriesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/suggestion-categories/stream';
};

export type GetSuggestionCategoriesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventSuggestionCategory>;
};

export type GetSuggestionCategoriesStreamResponse = GetSuggestionCategoriesStreamResponses[keyof GetSuggestionCategoriesStreamResponses];

export type DeleteSuggestionCategoriesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}';
};

export type DeleteSuggestionCategoriesByIdResponses = {
    /**
     * OK
     */
    200: SuggestionCategory;
};

export type DeleteSuggestionCategoriesByIdResponse = DeleteSuggestionCategoriesByIdResponses[keyof DeleteSuggestionCategoriesByIdResponses];

export type GetSuggestionCategoriesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}';
};

export type GetSuggestionCategoriesByIdResponses = {
    /**
     * OK
     */
    200: SuggestionCategory;
};

export type GetSuggestionCategoriesByIdResponse = GetSuggestionCategoriesByIdResponses[keyof GetSuggestionCategoriesByIdResponses];

export type PatchSuggestionCategoriesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}';
};

export type PatchSuggestionCategoriesByIdResponses = {
    /**
     * OK
     */
    200: SuggestionCategory;
};

export type PatchSuggestionCategoriesByIdResponse = PatchSuggestionCategoriesByIdResponses[keyof PatchSuggestionCategoriesByIdResponses];

export type PutSuggestionCategoriesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}';
};

export type PutSuggestionCategoriesByIdResponses = {
    /**
     * OK
     */
    200: SuggestionCategory;
};

export type PutSuggestionCategoriesByIdResponse = PutSuggestionCategoriesByIdResponses[keyof PutSuggestionCategoriesByIdResponses];

export type DeleteSuggestionCategoriesByIdDocTypeFieldData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}/doc-type-field';
};

export type DeleteSuggestionCategoriesByIdDocTypeFieldResponses = {
    /**
     * OK
     */
    200: SuggestionCategory;
};

export type DeleteSuggestionCategoriesByIdDocTypeFieldResponse = DeleteSuggestionCategoriesByIdDocTypeFieldResponses[keyof DeleteSuggestionCategoriesByIdDocTypeFieldResponses];

export type GetSuggestionCategoriesByIdDocTypeFieldsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/suggestion-categories/{id}/doc-type-fields';
};

export type GetSuggestionCategoriesByIdDocTypeFieldsResponses = {
    /**
     * OK
     */
    200: PageDocTypeField;
};

export type GetSuggestionCategoriesByIdDocTypeFieldsResponse = GetSuggestionCategoriesByIdDocTypeFieldsResponses[keyof GetSuggestionCategoriesByIdDocTypeFieldsResponses];

export type DeleteSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdData = {
    body?: never;
    path: {
        docTypeFieldId: number;
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}/doc-type-fields/{docTypeFieldId}';
};

export type DeleteSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponses = {
    /**
     * OK
     */
    200: Tuple2SuggestionCategoryDocTypeField;
};

export type DeleteSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponse = DeleteSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponses[keyof DeleteSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponses];

export type PutSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdData = {
    body?: never;
    path: {
        docTypeFieldId: number;
        id: number;
    };
    query?: never;
    url: '/suggestion-categories/{id}/doc-type-fields/{docTypeFieldId}';
};

export type PutSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponses = {
    /**
     * OK
     */
    200: Tuple2SuggestionCategoryDocTypeField;
};

export type PutSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponse = PutSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponses[keyof PutSuggestionCategoriesByIdDocTypeFieldsByDocTypeFieldIdResponses];

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/templates';
};

export type GetTemplatesResponses = {
    /**
     * OK
     */
    200: PageDocTypeTemplate;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type PostTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates';
};

export type PostTemplatesResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type PostTemplatesResponse = PostTemplatesResponses[keyof PostTemplatesResponses];

export type GetTemplatesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates/count';
};

export type GetTemplatesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetTemplatesCountResponse = GetTemplatesCountResponses[keyof GetTemplatesCountResponses];

export type GetTemplatesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates/stream';
};

export type GetTemplatesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventDocTypeTemplate>;
};

export type GetTemplatesStreamResponse = GetTemplatesStreamResponses[keyof GetTemplatesStreamResponses];

export type DeleteTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type DeleteTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type DeleteTemplatesByIdResponse = DeleteTemplatesByIdResponses[keyof DeleteTemplatesByIdResponses];

export type GetTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type GetTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type GetTemplatesByIdResponse = GetTemplatesByIdResponses[keyof GetTemplatesByIdResponses];

export type PatchTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type PatchTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type PatchTemplatesByIdResponse = PatchTemplatesByIdResponses[keyof PatchTemplatesByIdResponses];

export type PutTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type PutTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type PutTemplatesByIdResponse = PutTemplatesByIdResponses[keyof PutTemplatesByIdResponses];

export type GetTemplatesByIdCompiledData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}/compiled';
};

export type GetTemplatesByIdCompiledResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetTemplatesByIdCompiledResponse = GetTemplatesByIdCompiledResponses[keyof GetTemplatesByIdCompiledResponses];

export type PostV1DataIndexAutoGenerateDocTypesData = {
    body: AutoGenerateDocTypesRequest;
    path?: never;
    query?: never;
    url: '/v1/data-index/auto-generate-doc-types';
};

export type PostV1DataIndexAutoGenerateDocTypesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1DataIndexAutoGenerateDocTypesError = PostV1DataIndexAutoGenerateDocTypesErrors[keyof PostV1DataIndexAutoGenerateDocTypesErrors];

export type PostV1DataIndexAutoGenerateDocTypesResponses = {
    /**
     * Successful DocType Auto generation
     */
    204: void;
};

export type PostV1DataIndexAutoGenerateDocTypesResponse = PostV1DataIndexAutoGenerateDocTypesResponses[keyof PostV1DataIndexAutoGenerateDocTypesResponses];

export type PostV1DataIndexCreateDataIndexFromDocTypesByDatasourceIdData = {
    body?: never;
    path: {
        datasourceId: number;
    };
    query?: never;
    url: '/v1/data-index/create-data-index-from-doc-types/{datasourceId}';
};

export type PostV1DataIndexCreateDataIndexFromDocTypesByDatasourceIdResponses = {
    /**
     * OK
     */
    200: DataIndex;
};

export type PostV1DataIndexCreateDataIndexFromDocTypesByDatasourceIdResponse = PostV1DataIndexCreateDataIndexFromDocTypesByDatasourceIdResponses[keyof PostV1DataIndexCreateDataIndexFromDocTypesByDatasourceIdResponses];

export type PostV1DataIndexGetMappingsFromDocTypesData = {
    body: GetMappingsOrSettingsFromDocTypesRequest;
    path?: never;
    query?: never;
    url: '/v1/data-index/get-mappings-from-doc-types';
};

export type PostV1DataIndexGetMappingsFromDocTypesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1DataIndexGetMappingsFromDocTypesError = PostV1DataIndexGetMappingsFromDocTypesErrors[keyof PostV1DataIndexGetMappingsFromDocTypesErrors];

export type PostV1DataIndexGetMappingsFromDocTypesResponses = {
    /**
     * Related Index Mapping
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostV1DataIndexGetMappingsFromDocTypesResponse = PostV1DataIndexGetMappingsFromDocTypesResponses[keyof PostV1DataIndexGetMappingsFromDocTypesResponses];

export type PostV1DataIndexGetSettingsFromDocTypesData = {
    body: GetMappingsOrSettingsFromDocTypesRequest;
    path?: never;
    query?: never;
    url: '/v1/data-index/get-settings-from-doc-types';
};

export type PostV1DataIndexGetSettingsFromDocTypesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1DataIndexGetSettingsFromDocTypesError = PostV1DataIndexGetSettingsFromDocTypesErrors[keyof PostV1DataIndexGetSettingsFromDocTypesErrors];

export type PostV1DataIndexGetSettingsFromDocTypesResponses = {
    /**
     * Related Index Settings
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostV1DataIndexGetSettingsFromDocTypesResponse = PostV1DataIndexGetSettingsFromDocTypesResponses[keyof PostV1DataIndexGetSettingsFromDocTypesResponses];

export type GetV1DateFilterData = {
    body?: never;
    path?: never;
    query?: {
        translated?: boolean;
    };
    url: '/v1/date-filter';
};

export type GetV1DateFilterResponses = {
    /**
     * OK
     */
    200: Array<DocTypeFieldResponseDto>;
};

export type GetV1DateFilterResponse = GetV1DateFilterResponses[keyof GetV1DateFilterResponses];

export type PostV1IndexReindexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/index/reindex';
};

export type PostV1IndexReindexResponses = {
    /**
     * OK
     */
    200: Array<DatasourceJobStatus>;
};

export type PostV1IndexReindexResponse = PostV1IndexReindexResponses[keyof PostV1IndexReindexResponses];

export type PostV1SearchConfigByIdConfigureHybridSearchData = {
    body: HybridSearchPipelineDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/search-config/{id}/configure-hybrid-search';
};

export type PostV1SearchConfigByIdConfigureHybridSearchErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1SearchConfigByIdConfigureHybridSearchError = PostV1SearchConfigByIdConfigureHybridSearchErrors[keyof PostV1SearchConfigByIdConfigureHybridSearchErrors];

export type PostV1SearchConfigByIdConfigureHybridSearchResponses = {
    /**
     * Hybrid search configure successfully
     */
    200: SearchPipelineResponseDto;
};

export type PostV1SearchConfigByIdConfigureHybridSearchResponse = PostV1SearchConfigByIdConfigureHybridSearchResponses[keyof PostV1SearchConfigByIdConfigureHybridSearchResponses];

export type PostV1TriggerData = {
    body: TriggerResourceDto;
    path?: never;
    query?: never;
    url: '/v1/trigger';
};

export type PostV1TriggerResponses = {
    /**
     * OK
     */
    200: Array<DatasourceJobStatus>;
};

export type PostV1TriggerResponse = PostV1TriggerResponses[keyof PostV1TriggerResponses];

export type PostV2TriggerData = {
    body: TriggerV2ResourceDto;
    path?: never;
    query?: never;
    url: '/v2/trigger';
};

export type PostV2TriggerErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV2TriggerError = PostV2TriggerErrors[keyof PostV2TriggerErrors];

export type PostV2TriggerResponses = {
    /**
     * Auto Generate successful
     */
    200: TriggerResponse;
};

export type PostV2TriggerResponse = PostV2TriggerResponses[keyof PostV2TriggerResponses];
