// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Action = 'CREATE' | 'OVERWRITE' | 'SKIP';

export type AutoGenerateDocTypesRequest = {
    datasourceId?: number;
};

export type CombinationTechnique = 'ARITHMETIC_MEAN' | 'GEOMETRIC_MEAN' | 'ARMONIC_MEAN';

export type ConfigEntity = {
    ref?: string;
    type?: ConfigEntityType;
    key?: string;
    attributes?: unknown;
    references?: {
        [key: string]: Array<string>;
    };
    redactedFields?: Array<string>;
};

export type ConfigEntityType = 'BUCKET' | 'DATASOURCE' | 'PLUGIN_DRIVER' | 'ENRICH_PIPELINE' | 'ENRICH_PIPELINE_ITEM' | 'ENRICH_ITEM' | 'DOC_TYPE' | 'DOC_TYPE_FIELD' | 'DOC_TYPE_TEMPLATE' | 'ANALYZER' | 'CHAR_FILTER' | 'TOKEN_FILTER' | 'TOKENIZER' | 'ACL_MAPPING' | 'QUERY_ANALYSIS' | 'ANNOTATOR' | 'RULE' | 'QUERY_PARSER_CONFIG' | 'SEARCH_CONFIG' | 'EMBEDDING_MODEL' | 'LARGE_LANGUAGE_MODEL' | 'LANGUAGE' | 'RAG_CONFIGURATION' | 'SUGGESTION_CATEGORY' | 'TAB' | 'SORTING' | 'TOKEN_TAB' | 'AUTOCOMPLETE' | 'AUTOCORRECTION' | 'HIGHLIGHT';

export type ConfigMetadata = {
    exportedAt?: string;
    sourceVirtualHost?: string;
    activeBucketRef?: string;
    enabledEmbeddingModelRef?: string;
    enabledLargeLanguageModelRef?: string;
};

export type ConfigPackage = {
    schemaVersion?: string;
    metadata?: ConfigMetadata;
    entities?: Array<ConfigEntity>;
};

export type DocType = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
};

export type DocTypeTemplate = {
    id?: number;
    createDate?: string;
    modifiedDate?: string;
    name?: string;
    description?: string;
    templateType?: TemplateType;
    source?: string;
    compiled?: string;
};

export type EventType = 'CREATE' | 'UPDATE' | 'DELETE';

export type FieldValue = {
    value?: unknown;
    isDefault?: boolean;
};

export type FormField = {
    info?: string;
    label?: string;
    name?: string;
    type?: FormFieldType;
    size?: number;
    required?: boolean;
    values?: Array<FieldValue>;
    validator?: FormFieldValidator;
};

export type FormFieldType = 'text' | 'number' | 'select' | 'multiselect' | 'list' | 'date' | 'email' | 'password' | 'time' | 'url' | 'checkbox' | 'stringMap';

export type FormFieldValidator = {
    min?: number;
    max?: number;
    regex?: string;
};

export type FormTemplate = {
    fields?: Array<FormField>;
};

export type GetMappingsOrSettingsFromDocTypesRequest = {
    docTypeIds?: Array<number>;
};

export type HealthDto = {
    status: Status;
};

export type HybridSearchPipelineDto = {
    normalizationTechnique?: NormalizationTechnique;
    combinationTechnique?: CombinationTechnique;
    weights?: Array<number>;
};

export type ImportMode = 'OVERWRITE' | 'SKIP';

export type ImportReport = {
    dryRun?: boolean;
    applied?: boolean;
    mode?: ImportMode;
    actions?: Array<PlannedAction>;
    created?: number;
    overwritten?: number;
    skipped?: number;
    missingReferences?: Array<MissingReference>;
    secretsToReenter?: Array<SecretToReenter>;
    blockingErrors?: Array<string>;
    resolvedIds?: {
        [key: string]: number;
    };
};

export type JobStatus = 'TRIGGER_RUNNING' | 'REINDEX_RUNNING' | 'NOT_RUNNING';

export type K9Column = 'id' | 'name' | 'description' | 'createDate' | 'modifiedDate';

export type K9EntityEventDocTypeTemplate = {
    type?: EventType;
    entity?: DocTypeTemplate;
    previousEntity?: DocTypeTemplate;
};

export type MissingReference = {
    fromRef?: string;
    fromKey?: string;
    relationship?: string;
    targetHandle?: string;
};

export type NormalizationTechnique = 'MIN_MAX' | 'L2';

export type PageDocTypeTemplate = Array<DocTypeTemplate>;

export type PlannedAction = {
    ref?: string;
    type?: ConfigEntityType;
    action?: Action;
    existingId?: number;
};

export type PluginDriverDto = {
    name: string;
    description?: string;
    type: PluginDriverType;
    provisioning?: Provisioning;
    resourceUri?: ResourceUri;
};

export type PluginDriverDocType = {
    docTypeId?: number;
    name?: string;
    selected?: boolean;
};

export type PluginDriverDocTypesDto = {
    docTypes?: Array<PluginDriverDocType>;
};

export type PluginDriverType = 'HTTP';

/**
 * Problem details for HTTP APIs (rfc7807)
 */
export type Problem = {
    /**
     * An absolute URI that identifies the problem type.
     */
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    /**
     * An absolute URI that identifies the specific occurrence of the problem.
     */
    instance?: string;
};

export type Provisioning = 'SYSTEM' | 'USER';

export type ResourceUri = {
    baseUri?: string;
    path?: string;
};

export type SchedulingStatus = 'ALLOWED' | 'BLOCKED';

export type SearchPipelineResponseDto = {
    status?: number;
    body?: string;
    reason?: string;
};

export type SecretToReenter = {
    ref?: string;
    key?: string;
    type?: ConfigEntityType;
    fields?: Array<string>;
};

export type Status = 'UP' | 'DOWN' | 'UNKNOWN';

export type TemplateType = 'JAVASCRIPT_SOURCE' | 'TYPESCRIPT_SOURCE' | 'JAVASCRIPT_COMPILED';

export type TriggerResponse = {
    oldJobStatus?: JobStatus;
    status?: SchedulingStatus;
};

export type TriggerV2ResourceDto = {
    datasourceId?: number;
    reindex?: boolean;
    startIngestionDate?: string;
};

export type GetBucketsCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current';
};

export type GetBucketsCurrentErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentError = GetBucketsCurrentErrors[keyof GetBucketsCurrentErrors];

export type GetBucketsCurrentResponses = {
    /**
     * Current Bucket configuration returned
     */
    200: unknown;
};

export type GetBucketsCurrentAvailableLanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/availableLanguage';
};

export type GetBucketsCurrentAvailableLanguageErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentAvailableLanguageError = GetBucketsCurrentAvailableLanguageErrors[keyof GetBucketsCurrentAvailableLanguageErrors];

export type GetBucketsCurrentAvailableLanguageResponses = {
    /**
     * List of available Languages returned
     */
    200: unknown;
};

export type GetBucketsCurrentDatasourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/datasources';
};

export type GetBucketsCurrentDatasourcesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentDatasourcesError = GetBucketsCurrentDatasourcesErrors[keyof GetBucketsCurrentDatasourcesErrors];

export type GetBucketsCurrentDatasourcesResponses = {
    /**
     * List of Datasources returned
     */
    200: unknown;
};

export type GetBucketsCurrentDefaultLanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/defaultLanguage';
};

export type GetBucketsCurrentDefaultLanguageErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentDefaultLanguageError = GetBucketsCurrentDefaultLanguageErrors[keyof GetBucketsCurrentDefaultLanguageErrors];

export type GetBucketsCurrentDefaultLanguageResponses = {
    /**
     * Default Language returned
     */
    200: unknown;
};

export type GetBucketsCurrentDocTypeFieldsSortableData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/doc-type-fields-sortable';
};

export type GetBucketsCurrentDocTypeFieldsSortableErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentDocTypeFieldsSortableError = GetBucketsCurrentDocTypeFieldsSortableErrors[keyof GetBucketsCurrentDocTypeFieldsSortableErrors];

export type GetBucketsCurrentDocTypeFieldsSortableResponses = {
    /**
     * List of Sortable DocTypeFields returned
     */
    200: unknown;
};

export type GetBucketsCurrentSortingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/sortings';
};

export type GetBucketsCurrentSortingsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentSortingsError = GetBucketsCurrentSortingsErrors[keyof GetBucketsCurrentSortingsErrors];

export type GetBucketsCurrentSortingsResponses = {
    /**
     * List of Sortings returned
     */
    200: unknown;
};

export type GetBucketsCurrentSuggestionCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/suggestionCategories';
};

export type GetBucketsCurrentSuggestionCategoriesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentSuggestionCategoriesError = GetBucketsCurrentSuggestionCategoriesErrors[keyof GetBucketsCurrentSuggestionCategoriesErrors];

export type GetBucketsCurrentSuggestionCategoriesResponses = {
    /**
     * List of Suggestion Categories returned
     */
    200: unknown;
};

export type GetBucketsCurrentTabsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If return translations
         */
        translated?: boolean;
    };
    url: '/buckets/current/tabs';
};

export type GetBucketsCurrentTabsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentTabsError = GetBucketsCurrentTabsErrors[keyof GetBucketsCurrentTabsErrors];

export type GetBucketsCurrentTabsResponses = {
    /**
     * List of Tabs returned
     */
    200: unknown;
};

export type GetBucketsCurrentTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buckets/current/templates';
};

export type GetBucketsCurrentTemplatesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetBucketsCurrentTemplatesError = GetBucketsCurrentTemplatesErrors[keyof GetBucketsCurrentTemplatesErrors];

export type GetBucketsCurrentTemplatesResponses = {
    /**
     * List of Templates returned
     */
    200: unknown;
};

export type FormData = {
    body: ResourceUri;
    path?: never;
    query?: never;
    url: '/enrichers/form';
};

export type FormErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * The service does not expose a form endpoint or returned an invalid response
     */
    502: Problem;
};

export type FormError = FormErrors[keyof FormErrors];

export type FormResponses = {
    /**
     * Form returned
     */
    200: unknown;
};

export type HealthData = {
    body: ResourceUri;
    path?: never;
    query?: never;
    url: '/enrichers/health';
};

export type HealthErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * Health Check Ok
     */
    200: unknown;
};

export type PostPipelineCallbackByTokenIdData = {
    body?: never;
    path: {
        'token-id': string;
    };
    query?: never;
    url: '/pipeline/callback/{token-id}';
};

export type PostPipelineCallbackByTokenIdResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetPluginDriversDocumentTypesByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/documentTypes/{id}';
};

export type GetPluginDriversDocumentTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetPluginDriversDocumentTypesByIdError = GetPluginDriversDocumentTypesByIdErrors[keyof GetPluginDriversDocumentTypesByIdErrors];

export type GetPluginDriversDocumentTypesByIdResponses = {
    /**
     * The list of the Document Types created from this Plugin Driver
     */
    200: PluginDriverDocTypesDto;
};

export type GetPluginDriversDocumentTypesByIdResponse = GetPluginDriversDocumentTypesByIdResponses[keyof GetPluginDriversDocumentTypesByIdResponses];

export type PostPluginDriversDocumentTypesByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/documentTypes/{id}';
};

export type PostPluginDriversDocumentTypesByIdResponses = {
    /**
     * OK
     */
    200: Array<DocType>;
};

export type PostPluginDriversDocumentTypesByIdResponse = PostPluginDriversDocumentTypesByIdResponses[keyof PostPluginDriversDocumentTypesByIdResponses];

export type GetPluginDriversFormByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/form/{id}';
};

export type GetPluginDriversFormByIdErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * The service does not expose a form endpoint or returned an invalid response
     */
    502: Problem;
};

export type GetPluginDriversFormByIdError = GetPluginDriversFormByIdErrors[keyof GetPluginDriversFormByIdErrors];

export type GetPluginDriversFormByIdResponses = {
    /**
     * Form returned
     */
    200: FormTemplate;
};

export type GetPluginDriversFormByIdResponse = GetPluginDriversFormByIdResponses[keyof GetPluginDriversFormByIdResponses];

export type PostPluginDriversHealthData = {
    body: PluginDriverDto;
    path?: never;
    query?: never;
    url: '/pluginDrivers/health';
};

export type PostPluginDriversHealthErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostPluginDriversHealthError = PostPluginDriversHealthErrors[keyof PostPluginDriversHealthErrors];

export type PostPluginDriversHealthResponses = {
    /**
     * Plugin Driver Health Status
     */
    200: HealthDto;
};

export type PostPluginDriversHealthResponse = PostPluginDriversHealthResponses[keyof PostPluginDriversHealthResponses];

export type GetPluginDriversHealthByIdData = {
    body?: never;
    path: {
        /**
         * Plugin Driver's id
         */
        id: number;
    };
    query?: never;
    url: '/pluginDrivers/health/{id}';
};

export type GetPluginDriversHealthByIdErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetPluginDriversHealthByIdError = GetPluginDriversHealthByIdErrors[keyof GetPluginDriversHealthByIdErrors];

export type GetPluginDriversHealthByIdResponses = {
    /**
     * Plugin Driver Health Status
     */
    200: HealthDto;
};

export type GetPluginDriversHealthByIdResponse = GetPluginDriversHealthByIdResponses[keyof GetPluginDriversHealthByIdResponses];

export type PostSchedulersBySchedulerIdCancelSchedulingData = {
    body?: never;
    path: {
        /**
         * Scheduler entity ID
         */
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/cancelScheduling';
};

export type PostSchedulersBySchedulerIdCancelSchedulingErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostSchedulersBySchedulerIdCancelSchedulingError = PostSchedulersBySchedulerIdCancelSchedulingErrors[keyof PostSchedulersBySchedulerIdCancelSchedulingErrors];

export type PostSchedulersBySchedulerIdCancelSchedulingResponses = {
    /**
     * Scheduling cancelled
     */
    204: void;
};

export type PostSchedulersBySchedulerIdCancelSchedulingResponse = PostSchedulersBySchedulerIdCancelSchedulingResponses[keyof PostSchedulersBySchedulerIdCancelSchedulingResponses];

export type PostSchedulersBySchedulerIdCloseSchedulingData = {
    body?: never;
    path: {
        /**
         * Scheduler entity ID
         */
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/closeScheduling';
};

export type PostSchedulersBySchedulerIdCloseSchedulingErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostSchedulersBySchedulerIdCloseSchedulingError = PostSchedulersBySchedulerIdCloseSchedulingErrors[keyof PostSchedulersBySchedulerIdCloseSchedulingErrors];

export type PostSchedulersBySchedulerIdCloseSchedulingResponses = {
    /**
     * Scheduling closed
     */
    204: void;
};

export type PostSchedulersBySchedulerIdCloseSchedulingResponse = PostSchedulersBySchedulerIdCloseSchedulingResponses[keyof PostSchedulersBySchedulerIdCloseSchedulingResponses];

export type GetSchedulersBySchedulerIdGetDeletedContentIdsData = {
    body?: never;
    path: {
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/getDeletedContentIds';
};

export type GetSchedulersBySchedulerIdGetDeletedContentIdsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetSchedulersBySchedulerIdGetDeletedContentIdsError = GetSchedulersBySchedulerIdGetDeletedContentIdsErrors[keyof GetSchedulersBySchedulerIdGetDeletedContentIdsErrors];

export type GetSchedulersBySchedulerIdGetDeletedContentIdsResponses = {
    /**
     * List of deleted content ids returned
     */
    200: Array<unknown>;
};

export type GetSchedulersBySchedulerIdGetDeletedContentIdsResponse = GetSchedulersBySchedulerIdGetDeletedContentIdsResponses[keyof GetSchedulersBySchedulerIdGetDeletedContentIdsResponses];

export type PostSchedulersBySchedulerIdRerouteSchedulingData = {
    body?: never;
    path: {
        /**
         * Scheduler entity ID
         */
        schedulerId: number;
    };
    query?: never;
    url: '/schedulers/{schedulerId}/rerouteScheduling';
};

export type PostSchedulersBySchedulerIdRerouteSchedulingErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostSchedulersBySchedulerIdRerouteSchedulingError = PostSchedulersBySchedulerIdRerouteSchedulingErrors[keyof PostSchedulersBySchedulerIdRerouteSchedulingErrors];

export type PostSchedulersBySchedulerIdRerouteSchedulingResponses = {
    /**
     * Scheduling rerouted successfully
     */
    204: void;
};

export type PostSchedulersBySchedulerIdRerouteSchedulingResponse = PostSchedulersBySchedulerIdRerouteSchedulingResponses[keyof PostSchedulersBySchedulerIdRerouteSchedulingResponses];

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        after_id?: number;
        before_id?: number;
        limit?: number;
        searchText?: string;
        sortBy?: K9Column & unknown;
    };
    url: '/templates';
};

export type GetTemplatesResponses = {
    /**
     * OK
     */
    200: PageDocTypeTemplate;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type PostTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates';
};

export type PostTemplatesResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type PostTemplatesResponse = PostTemplatesResponses[keyof PostTemplatesResponses];

export type GetTemplatesCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates/count';
};

export type GetTemplatesCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetTemplatesCountResponse = GetTemplatesCountResponses[keyof GetTemplatesCountResponses];

export type GetTemplatesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates/stream';
};

export type GetTemplatesStreamResponses = {
    /**
     * OK
     */
    200: Array<K9EntityEventDocTypeTemplate>;
};

export type GetTemplatesStreamResponse = GetTemplatesStreamResponses[keyof GetTemplatesStreamResponses];

export type DeleteTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type DeleteTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type DeleteTemplatesByIdResponse = DeleteTemplatesByIdResponses[keyof DeleteTemplatesByIdResponses];

export type GetTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type GetTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type GetTemplatesByIdResponse = GetTemplatesByIdResponses[keyof GetTemplatesByIdResponses];

export type PatchTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type PatchTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type PatchTemplatesByIdResponse = PatchTemplatesByIdResponses[keyof PatchTemplatesByIdResponses];

export type PutTemplatesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type PutTemplatesByIdResponses = {
    /**
     * OK
     */
    200: DocTypeTemplate;
};

export type PutTemplatesByIdResponse = PutTemplatesByIdResponses[keyof PutTemplatesByIdResponses];

export type GetTemplatesByIdCompiledData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/templates/{id}/compiled';
};

export type GetTemplatesByIdCompiledResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetTemplatesByIdCompiledResponse = GetTemplatesByIdCompiledResponses[keyof GetTemplatesByIdCompiledResponses];

export type GetV1ConfigExportData = {
    body?: never;
    path?: never;
    query?: {
        includeDependencies?: boolean;
        types?: Array<ConfigEntityType>;
    };
    url: '/v1/config/export';
};

export type GetV1ConfigExportResponses = {
    /**
     * OK
     */
    200: ConfigPackage;
};

export type GetV1ConfigExportResponse = GetV1ConfigExportResponses[keyof GetV1ConfigExportResponses];

export type PostV1ConfigImportData = {
    body?: never;
    path?: never;
    query?: {
        dryRun?: boolean;
        mode?: ImportMode & unknown;
    };
    url: '/v1/config/import';
};

export type PostV1ConfigImportResponses = {
    /**
     * OK
     */
    200: ImportReport;
};

export type PostV1ConfigImportResponse = PostV1ConfigImportResponses[keyof PostV1ConfigImportResponses];

export type PostV1DataIndexAutoGenerateDocTypesData = {
    body: AutoGenerateDocTypesRequest;
    path?: never;
    query?: never;
    url: '/v1/data-index/auto-generate-doc-types';
};

export type PostV1DataIndexAutoGenerateDocTypesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1DataIndexAutoGenerateDocTypesError = PostV1DataIndexAutoGenerateDocTypesErrors[keyof PostV1DataIndexAutoGenerateDocTypesErrors];

export type PostV1DataIndexAutoGenerateDocTypesResponses = {
    /**
     * Successful DocType Auto generation
     */
    204: void;
};

export type PostV1DataIndexAutoGenerateDocTypesResponse = PostV1DataIndexAutoGenerateDocTypesResponses[keyof PostV1DataIndexAutoGenerateDocTypesResponses];

export type PostV1DataIndexGetMappingsFromDocTypesData = {
    body: GetMappingsOrSettingsFromDocTypesRequest;
    path?: never;
    query?: never;
    url: '/v1/data-index/get-mappings-from-doc-types';
};

export type PostV1DataIndexGetMappingsFromDocTypesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1DataIndexGetMappingsFromDocTypesError = PostV1DataIndexGetMappingsFromDocTypesErrors[keyof PostV1DataIndexGetMappingsFromDocTypesErrors];

export type PostV1DataIndexGetMappingsFromDocTypesResponses = {
    /**
     * Related Index Mapping
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostV1DataIndexGetMappingsFromDocTypesResponse = PostV1DataIndexGetMappingsFromDocTypesResponses[keyof PostV1DataIndexGetMappingsFromDocTypesResponses];

export type PostV1DataIndexGetSettingsFromDocTypesData = {
    body: GetMappingsOrSettingsFromDocTypesRequest;
    path?: never;
    query?: never;
    url: '/v1/data-index/get-settings-from-doc-types';
};

export type PostV1DataIndexGetSettingsFromDocTypesErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1DataIndexGetSettingsFromDocTypesError = PostV1DataIndexGetSettingsFromDocTypesErrors[keyof PostV1DataIndexGetSettingsFromDocTypesErrors];

export type PostV1DataIndexGetSettingsFromDocTypesResponses = {
    /**
     * Related Index Settings
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostV1DataIndexGetSettingsFromDocTypesResponse = PostV1DataIndexGetSettingsFromDocTypesResponses[keyof PostV1DataIndexGetSettingsFromDocTypesResponses];

export type PostV1SearchConfigByIdConfigureHybridSearchData = {
    body: HybridSearchPipelineDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/search-config/{id}/configure-hybrid-search';
};

export type PostV1SearchConfigByIdConfigureHybridSearchErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV1SearchConfigByIdConfigureHybridSearchError = PostV1SearchConfigByIdConfigureHybridSearchErrors[keyof PostV1SearchConfigByIdConfigureHybridSearchErrors];

export type PostV1SearchConfigByIdConfigureHybridSearchResponses = {
    /**
     * Hybrid search configure successfully
     */
    200: SearchPipelineResponseDto;
};

export type PostV1SearchConfigByIdConfigureHybridSearchResponse = PostV1SearchConfigByIdConfigureHybridSearchResponses[keyof PostV1SearchConfigByIdConfigureHybridSearchResponses];

export type PostV2TriggerData = {
    body: TriggerV2ResourceDto;
    path?: never;
    query?: never;
    url: '/v2/trigger';
};

export type PostV2TriggerErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Not found
     */
    404: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PostV2TriggerError = PostV2TriggerErrors[keyof PostV2TriggerErrors];

export type PostV2TriggerResponses = {
    /**
     * Auto Generate successful
     */
    200: TriggerResponse;
};

export type PostV2TriggerResponse = PostV2TriggerResponses[keyof PostV2TriggerResponses];
