# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Push Docker Osgi Images

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  osgi-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Plugin Driver Manager
        run: |
          ./mvnw install -Pbom --batch-mode
          ./mvnw install -Passemblies -pl assemblies/plugin-driver-manager/plugin-driver-manager-kar -am --batch-mode
          ./mvnw -Passemblies --file assemblies/plugin-driver-manager/plugin-driver-manager-karaf package jib:build -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }} --batch-mode


      - name: Build and Push Searcher
        run: |
          ./mvnw install -Pbom --batch-mode
          ./mvnw install -Passemblies -pl assemblies/searcher/searcher-kar -am --batch-mode
          ./mvnw -Passemblies --file assemblies/searcher/searcher-karaf package jib:build -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }} --batch-mode


      - name: Build and Push Index Writer
        run: |
          ./mvnw install -Pbom --batch-mode
          ./mvnw install -Passemblies -pl assemblies/index-writer/index-writer-kar -am --batch-mode
          ./mvnw -Passemblies --file assemblies/index-writer/index-writer-karaf package jib:build -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }} --batch-mode

